### ISSUE TITLE
Wrong date when editing a birthday

### ISSUE THREAD

**Issue by simonesestito** [m-i-n-a-r/birday#1]
When I try changing a birthday, a Bottomsheet will show up. Clicking on the date input, a calendar is opened correctly, but it is set to the current day instead of the birthday of the person I'm trying to edit.

**Comment by m-i-n-a-r** [comment]
Fixed in https://github.com/m-i-n-a-r/birday/commit/082e89b3832fadb7187e5226574050e44346b41e
