### ISSUE TITLE
Wrong date when modifying a new entry

### ISSUE THREAD

**Issue by skuethe** [m-i-n-a-r/birday#11]
Hey there, first off: great app! I very much like the effort and detail you put into the UI!

I stumbled upon some minor issue, most similar to:
#1 

If you create a new entry but have to modify the date before saving, the date selector will not use the already added date, but will go back to todays date.

So for example:
1. I create a new entry, enter user pre and surename and add the date 14. September 2001
2. I click "OK" on the date selector
3. I notice that I did not change the date - only the year. So I, again, click on the "select a date" selector
4. The date selector opens with todays date and todays year

Thanks again for your work!

**Comment by m-i-n-a-r** [comment]
Fixed in 88955615f16f3d50a9f15dc29ecb916f5ab11759
I'll release the update in Play Store in the next few days!
