### ISSUE TITLE
Add day, month, and year of original date to shareable text

### ISSUE THREAD

**Issue by russellbanks** [m-i-n-a-r/birday#119]
# Description
When sharing a reminder, it contains the name and the date of the next occurance. It would be helpful if this also contained the day, month and year of the original date.

For example, if I want to be able to share a birth date with a friend, I would still have to tell them the year and day of the week as this is not included in the sharable text. This is applicable for all types of reminders (birthdays, anniversaries, etc).

## Current behaviour
![image](https://user-images.githubusercontent.com/74878137/163494379-8296016f-3da3-4714-9695-9c9abed4e281.png)

## Ideal behaviour
![image](https://user-images.githubusercontent.com/74878137/163494544-ae96d256-4a36-42d4-9097-b8b3187b7a42.png)

**Comment by m-i-n-a-r** [comment]
You're perfectly right! I'll add this line in the next update 👍

**Comment by m-i-n-a-r** [comment]
Done in bfbb0373a70adc3afd295676eee05e7876628fa2 and released in v 3.1.1, thanks for the suggestion!
