### ISSUE TITLE
button vibration forced in date selection screen

### ISSUE THREAD

**Issue by skuethe** [m-i-n-a-r/birday#12]
Just leaving some more minor issues I found using the app. As stated in #11 I really appreciate your work with this app.

Description:
If you deselect the "Vibration" Option in the Customizations (so "No vibrations when a button is pressed" is shown), the date selection screen will still vibrate during button press. So f.e. switching the day, switching the month or pressing on the year will all trigger a phone vibration.

Thanks!

**Comment by m-i-n-a-r** [comment]
I use https://github.com/afollestad/material-dialogs for the dialogs, so i have no control over the vibration as far as i know. I opened an [issue](https://github.com/afollestad/material-dialogs/issues/2021), but i can't change this at the moment 😞
