### ISSUE TITLE
The "(youngest|oldest) person" stat calculation is not taking months into account (it seems)

### ISSUE THREAD

**Issue by skuethe** [m-i-n-a-r/birday#13]
**Description:**
I have added two birthdays for People born in this year (February and the current month: September).
In the stats it is showing me the Person born in February as "the youngest person".

So it seems it is only respecting the Year as input. Mind my non-existing Kotlin skills, but it seems to be related to this one:
https://github.com/m-i-n-a-r/birday/blob/5f2c44a150dee3ed7ca39137ce50b5530c6ae89d/app/src/main/java/com/minar/birday/utilities/StatsGenerator.kt#L214

**Comment by m-i-n-a-r** [comment]
Fixed in cb9b6d2e96055cce2023d8127e98f9be46929ba6
I'll release the update in Play Store in the next few days!
