### ISSUE TITLE
Add sorting by event type

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#132]
Sorting by other criteria like the time of addition or alphabetically might also be neat, but too much metadata might bloat up the size of a database entry. It _is_ just text, but still, I doubt very many people need that many options.

**Comment by m-i-n-a-r** [comment]
Something similar is already on the todo list. I'd like to add a dropdown in the search bar to filter only a particular event type (of course, if at least one event of that type exists). The idea is to use icons instead of text, to save space, but honestly i have no idea of how i could do a dropdown with icons, and now i'm working on the widget 😄 
So, long story short: i want to do it, but i accept suggestions and it will take time 👍

**Comment by DominikNovosel** [comment]
`The idea is to use icons instead of text, to save space, but honestly i have no idea of how i could do a dropdown with icons`
Let me preface this by saying that I only have experience making user interfaces in HTML and CSS, so i don't know whether my suggestions will work in Material. 
Presumably, the issue you're facing is that Material doesn't support icons in dropdowns.
I've seen other apps handle this by making the dropdown "items" a column of circular buttons containing the icons that fades in and "drops" below the button that opens the dropdown and "winds" back up again. This might actually look more elegant, but we still have the issue of making self-explanatory icons for all the types of sorting.

**Comment by DominikNovosel** [comment]
Do most users know they need to long press something to see more information about it?

**Comment by m-i-n-a-r** [comment]
Done in 8f30bcbfa30d66470ce111e60af5ebe891774d67 and previous commits. The user can choose an event type to filter the list. I kept this filtering logic as easy as possible. I always keep in mind that Birday is used by a lot of senior users who want and deserve a simple and easy app 😄

**Comment by DominikNovosel** [comment]
Awesome!
Say, didn't we forget to credit @vatonbero for transliterating the Serbian translation to Latin?

**Comment by DominikNovosel** [comment]
It's here: https://github.com/vatonbero/birday/blob/master/app/src/main/res/values-b+sr+Latn/strings.xml
I guess he didn't submit a pull request.

**Comment by m-i-n-a-r** [comment]
If he doesn't submit a pull request, i'll take the file myself. i'll wait a couple days of course. I'd like to include it in v4.0.1 if possibile 😄

**Comment by DominikNovosel** [comment]
It would certainly be a shame to let our efforts go to waste. While the transliteration process itself was trivial, it took us both a long time to figure out how to make Android differentiate between the scripts and then show the correct one (part of this is the fault of some manufacturers' custom ROMs).
