### ISSUE TITLE
Widget changes

### ISSUE THREAD

**Issue by Kuladeep1996** [m-i-n-a-r/birday#144]
Can you provide an option to show only favourites in widgets

**Comment by m-i-n-a-r** [comment]
Instead of adding an entire option, i could simpy change the widget to only show favorites when "favorites only" is enabled for the notifications. I'll think about it!

**Comment by m-i-n-a-r** [comment]
I'll close this since i redesigned the widget entirely. If you feel that this issue persists for the new widget, feel free to reopen it.  😄 Birday 4.0.0 has been released in the Play Store beta channel and contains this redesigned widget
