### ISSUE TITLE
Show multiple contacts in the widget

### ISSUE THREAD

**Issue by MartinX3** [m-i-n-a-r/birday#151]
I want to migrate from an old birthday app.
It's widget lists multiple contacts (restricted by the widget size) on a white/black background respecting the system dark mode.

I would like to have this in birday, too.

And because of the transparent background It's hard for me too see the content, especially with the dark mode.

**Comment by m-i-n-a-r** [comment]
No problem, the next update will include a new and redesigned widget following the new material design guidelines. I can't give a precise eta, but I'm working on it (you can see the progress looking at the develop branch)

**Comment by m-i-n-a-r** [comment]
The new widget is finally done. I'm awfully slow, but my free time is limited. The update is currently in the beta channel, and the new widget contains the complete list of the events.
