### ISSUE TITLE
Support for Filtering and more Info fields

### ISSUE THREAD

**Issue by arshshaikh06** [m-i-n-a-r/birday#152]
It would be great if there was an option to add more details along side the name and date such as
1. Prefix [PlainText] - (eg. Sir, Dr., Prof., etc)
2. Suffix [PlainText] - (eg. could be used to distinguish between people having the same name)
3. Category [DropDown] - (eg. Friend / Family / Colleague / Acquaintance)

And some filtering logic could be created based on the Category or Event Type.

**Comment by m-i-n-a-r** [comment]
Thanks for the suggestion, this was one of the possible improvements, but i have to think how to do it to avoid complicating the app and the insertion process. The majority of people just enter a name and the optional surname. Regarding the filtering i'm going to work on an "event type filter", and i'll see what i can do 😄 Believe it or not, Birday is used by many 70+ years users, and i'm desperately trying to keep it simple while adding new features 👍

**Comment by m-i-n-a-r** [comment]
In v4.x.x, the app includes a filtering logic and imports prefix, suffic and middle name as part of the name/surname fields when importing from contacts. Feel free to open a separate issue if you feel that that's not enough, but in the meantime i'll close this one to keep things clean 😄
