### ISSUE TITLE
Create a Weblate/Crowdin project to simplify translating process

### ISSUE THREAD

**Issue by ShimonHoranek** [m-i-n-a-r/birday#154]
Now, the process of translating is not the most user-friendly and can discourage people from translating. Weblate and Crowdin both offer much better experience when translating. Please consider adding support for either of these.

**Comment by m-i-n-a-r** [comment]
That's surely a good idea, even if i wrote a guide in the Wiki. I'll see what I can do!

**Comment by m-i-n-a-r** [comment]
https://crowdin.com/project/birday done. I'm not experienced with this kind of product and i messed the project up a couple times before nailing the right configuration. I appreciate any suggestion and contribution. I'll update the Wiki and the README with the link to the project, then i'll close this issue 😄

**Comment by m-i-n-a-r** [comment]
An important issue: Crowdin automatically deletes some plurals for no reason, and the build process fails. No idea how to fix this, i can only disable Lint for this kind of issue

**Comment by m-i-n-a-r** [comment]
Lint disabled, and all up and running. I can close this, thanks for suggesting it!
