### ISSUE TITLE
Release APK on Github Releases

### ISSUE THREAD

**Issue by matchboxbananasynergy** [m-i-n-a-r/birday#155]
It would be great if APKs could be released alongside the source for each release for people who don't want to get their apps through an app store.

**Comment by m-i-n-a-r** [comment]
Ok, I'll do it starting from the next release. Once the release is done, I'll close the issue 🙂

**Comment by m-i-n-a-r** [comment]
Done in https://github.com/m-i-n-a-r/birday/releases/tag/v4.0.1, and i'll keep doing it for future releases of course 😄
