### ISSUE TITLE
Not importing other events

### ISSUE THREAD

**Issue by francois072** [m-i-n-a-r/birday#157]
Birday imports the default dates from the contacts just fine, but doesn't import custom events added to contacts.

Samsung A12, Android 12

**Comment by m-i-n-a-r** [comment]
Birday only searches in birthdays, anniversaries and "other" labelled events. What do you mean by "custom events"? The events with a custom label?

**Comment by m-i-n-a-r** [comment]
Closed while waiting for a response and additional context
