### ISSUE TITLE
Double import/sync contacts

### ISSUE THREAD

**Issue by albertopasqualetto** [m-i-n-a-r/birday#163]
First of all if I import my contacts twice, then the favourites are deleted.

Then, I think it would be wonderful having a sync between contacts and Birday, so if I add the year in Birday, then it will reflect to my contacts and vice versa, same thing if I add a new contact.

Besides from this, it is a very good app!

**Comment by m-i-n-a-r** [comment]
Regarding the first point, if a new contact is inserted and a duplicate is detected, the duplicate is overwritten (wich Is useful when importing multiple times from contacts), i'll see if i can keep the favorite status.

Birday can't write to contacts and i don't want ask more dangerous permissions.
I Will only add an automatic synchronization from contacts to Birday 🙂

**Comment by albertopasqualetto** [comment]
That's a good idea.
Thanks!

**Comment by m-i-n-a-r** [comment]
Auto-sync is now part of the experimental options, and it works as it should. Regarding the favorite status, i found no way to keep it when a duplicate is detected. I have to decide if an imported event has priority over a duplicate, already saved, event. At the time of writing, and as you wrote, the app consider any imported duplicate as the source of truth and overwrite the local copy. Feel free to reopen the issue if you have any suggestion

**Comment by albertopasqualetto** [comment]
Good!
When will the new version be released on play store?

**Comment by m-i-n-a-r** [comment]
It's currently in the beta channel (waiting for Google approval) and I'll release it in the stable channel later this month!

**Comment by albertopasqualetto** [comment]
Thanks!

**Comment by NinjaShiroi** [comment]
I'm not sure to understand why the source of truth matters for the favorite status.

If a contact is set as favorite in the contact app, is it supposed to be a favorite in the birday app?

1. If yes, right now, it does not seem to work when I import them from Contacts.
Also, in that case, could you add an extra option on this experimental feature?
The idea would be to have a toggle to let the favorites items be considered as source of truth (to avoid removing the favorite status) and for the rest keep the imported contact as source of truth. 

2. If not, why not just update the birday contacts with imported contact as a source of truth and just leave the favorite status as it is?
