### ISSUE TITLE
minor app issue

### ISSUE THREAD

**Issue by agamerawesome** [m-i-n-a-r/birday#164]
Febuary 19th shows up as aquarius while online it says pisces

**Comment by m-i-n-a-r** [comment]
Thanks for letting me know, i'll fix It as soon as possible!

**Comment by m-i-n-a-r** [comment]
d5a619015ca83c290590614b4cda6e6b98fa8d75 fixed it, even if i found conflicting opinions on this. Some still consider february 19th as aquarius 🤔
