### ISSUE TITLE
Death anniversaries are counted as birthdays

### ISSUE THREAD

**Issue by 825i** [m-i-n-a-r/birday#165]
When checking your statistics.
Anyone with a death anniversary is treated as x years old.

If the same person has a birthday and a death anniversary in the app (eg. if you wish to remember both). They can be both the oldest and youngest person on the statistics page.

I've emailed you a screenshot of this error.

**Comment by m-i-n-a-r** [comment]
Woah, i missed that one, thank you! I'll check the emails soon 🙂

**Comment by m-i-n-a-r** [comment]
This *SHOULD* be fixed in Birday 4.0.0 (currently in beta). Or at least, i can't recreate it anymore. Feel free to send me another mail or reopen the issue if you experience this issue in the latest release 😄
