### ISSUE TITLE
Local contact is not imported if it has the name suffix filled

### ISSUE THREAD

**Issue by zendynar** [m-i-n-a-r/birday#166]
I found a bug where if a contact has the name suffix filled with any text, it doesn't get imported into Birday, it is just skipped. As soon as the field is emptied, the import works and the contact is added.
![IMG_20220910_092255](https://user-images.githubusercontent.com/105803717/189473992-8a35275e-7aff-4082-9abb-b8751ce476d6.jpg)

I also checked name prefix, it works fine without issues.

Birday version is 3.1.1 from F-droid
My device is Oneplus 9 Pro, Android 12

**Comment by zendynar** [comment]
Just encountered another issue but with the nickname field - contact with a nickname field silently fails to import

**Comment by m-i-n-a-r** [comment]
I'll look into it as soon as possible, and sorry for the late reply!

**Comment by m-i-n-a-r** [comment]
It should be fixed in d81eb1fa1deef3813db4aee35ca8c0e216b596cf and other previous commits. Feel free to reopen this issue if you experience other issues in v4.x.x 😄
