### ISSUE TITLE
Birday resumes in the wrong orientation

### ISSUE THREAD

**Issue by russellbanks** [m-i-n-a-r/birday#188]
If you have the phone on its side, but have auto-rotate turned off, then pause and resume Birday, it will briefly have the wrong orientation.

https://user-images.githubusercontent.com/74878137/202649882-c7645609-61f4-4103-8eea-1f7899f695f1.mp4

**Comment by m-i-n-a-r** [comment]
Hi, thanks for letting me know! I can't recreate this issue on my devices. I turn off auto-rotate, i hold the phone in landscape and i recreate the steps in the video, but the app stays in portrait without rotating. So this could depend on the Android version or the device. Which device are you using?

**Comment by russellbanks** [comment]
> Which device are you using? 

A OnePlus 7t with Android 11

**Comment by m-i-n-a-r** [comment]
OK, Oxygen OS i guess, thanks. I'm currently running Android 12 (Samsung Rom), 10 and 13 (both Pixel style Roms) on my test devices and i can confirm i can't recreate it. If the issue still persists after a reboot or an app force stop on your device, i'll need to find an Android 11 Oxygen OS device 😟

**Comment by m-i-n-a-r** [comment]
Can you confirm this issue is still there after a reboot?

**Comment by russellbanks** [comment]
> Can you confirm this issue is still there after a reboot?

Yep, still present.

**Comment by m-i-n-a-r** [comment]
Thanks for confirming. I'm still unable to recreate it. Let's see if someone else can confirm this bug

**Comment by m-i-n-a-r** [comment]
After 4 months of nobody confirming this, i assume it's a device related issue. After all, Birday doesn't have a custom resume logic, and it should behave like every other app. 😄
