### ISSUE TITLE
[feature request] direct display of remarks

### ISSUE THREAD

**Issue by gbdomubpkm** [m-i-n-a-r/birday#189]
Thank you for this usefull app that I just discovered.

I would like a visible and direct display of the 'remarks'. Perhaps by a long press on the desired person?

Regards

**Comment by m-i-n-a-r** [comment]
I'm glad you like it. Do you mean the notes field?

**Comment by m-i-n-a-r** [comment]
I'll see what i can do. Currently, you can display it tapping on any favorite event or in the details!

**Comment by gbdomubpkm** [comment]
OK. Thank you for the info. In fact, the goal is to be able to quickly access one or two key memo info for a person in addition to the birthday. And if later, you implement a reminder (ringtone) for additional events concerning a person, it will be a plus.

**Comment by m-i-n-a-r** [comment]
After a survey among various users, the current ways of reaching the notes field are enough, and the quick information displayed on long press are thought to be more useful. SoI'll close this, but thanks for suggesting it 😄
