### ISSUE TITLE
android system navigation bar color

### ISSUE THREAD

**Issue by andsofine** [m-i-n-a-r/birday#191]
android navigation bar should be the same color as bottom app bar. 
the issue appeared in the latest version (4.0.1), probably due to the fact that now the bottom bar of the app changes color depending on the light/dark theme
![Screenshot_20221118-152956_1_1](https://user-images.githubusercontent.com/99369164/202708991-a9a35a76-0a44-4ebd-b023-57e4a40e555f.png)
![Screenshot_20221118-152945_1_1](https://user-images.githubusercontent.com/99369164/202709028-1ad0428a-4bf0-408f-9332-03e1a140cd45.png)

**Comment by m-i-n-a-r** [comment]
Rather than an issue, this is a choice, since i focused on supporting Material 3 and the dynamic coloring (on Android 12+ the navbar is indeed themed if you choose "monet" as accent). I'll try to support this feature on the other themes too!

**Comment by m-i-n-a-r** [comment]
I restored the old dark grey navbar and bottom action bar for non-Material You accent colors. I'll release it in v4.1.0, hopefully in a couple days 😄
