### ISSUE TITLE
Multiple events for each contact

### ISSUE THREAD

**Issue by nutpantz** [m-i-n-a-r/birday#194]
Right now it appears each event is individual.
It would be nice if all events were all listed for the contact when editing or viewing.

**Comment by m-i-n-a-r** [comment]
Birday is event-centric, not contact-centric. All i can think of is a way to list events having the same name in the details of a given event 🤔

**Comment by nutpantz** [comment]
I understand , adding and organizing events of easiest by contact. Recently i imported all my events after installing the app, and it was quite difficult to try and find all the events that were not imported. Anniversaries, deaths custom events. 
I still have no idea what is missing. 
But i understand, original design may preclude the ability.
