### ISSUE TITLE
Persistent Notification

### ISSUE THREAD

**Issue by bagarwa** [m-i-n-a-r/birday#196]
Right now, the Birday notifications are dismissable. With my bad habit of clicking "Clear all", while clearing other apps' unimportant notifications, I end up dismissing these Birday notifications too.

So, a useful option for me would be - Birday adding an option for notifications to be "Sticky" or "Persistant"; so that they don't get dismissed just by swiping away. Such notifications can have a "dismiss" action button which can be tapped to dismiss the notification. 

(I have more ideas about adding a second custom action button to those notifications; like "call" or "text" button that can be tapped to call the person via phone app or msg via the default msg app etc. But I digress. That's for another day.)

**Comment by m-i-n-a-r** [comment]
No problem, i'll add such option soon. It will be "experimental" and untranslated initially, but it should be available in the next release 😄

**Comment by m-i-n-a-r** [comment]
Done in 8f04e363867802fe3f9e6d68ef4be8daecc84727 
The "angry bird" mode enables shorter texts, persistent notification and other slight changes. Regarding other custom notification actions, feel free to open a separate issue 🙂
