### ISSUE TITLE
Widget customization 

### ISSUE THREAD

**Issue by bovergaauw** [m-i-n-a-r/birday#199]
It would be nice to allow for widget customization, especially colors. The previous version allowed me to have a black background, which was perfect for.

**Comment by m-i-n-a-r** [comment]
The previous widget (it will return in next release) only allowed black text, not black background. The current widget is adaptive and takes its colors from the system 🙂
Anyway, as i said, i added the old widget back and it will be customizable like it used to be!

**Comment by sonalder-darlene** [comment]
> The previous widget (it will return in next release) only allowed black text, not black background. The current widget is adaptive and takes its colors from the system 🙂 Anyway, as i said, i added the old widget back and it will be customizable like it used to be!

Good ! It was better with my launcher setup

**Comment by m-i-n-a-r** [comment]
Done in 3d6bc8c6b19d8c0723bec944351391b884ecbfdb. I'll release this feature in v4.1.0, hopefully in a couple days
