### ISSUE TITLE
First name doesn't accept the symbol -

### ISSUE THREAD

**Issue by tctovsli** [m-i-n-a-r/birday#2]
At least in Scandinavia, names can contain the symbol -, like Bob-Billy Lastname. The app doesn't.

**Comment by m-i-n-a-r** [comment]
Whoops, I simply didn't know that. I'll fix it asap!

**Comment by m-i-n-a-r** [comment]
Fixed in f03ffb1327591df47295c1e962faec768ecc3e7f 
I'll release the update in Play Store in the next few days
