### ISSUE TITLE
Do you consider to do multi language?

### ISSUE THREAD

**Issue by ghoevil** [m-i-n-a-r/birday#203]
Hi sir, I like this app. 
If so , I can translate to chinese when there's a string file available. tks.

**Comment by m-i-n-a-r** [comment]
Birday already supports 24 languages, including traditional chinese. If you mean simplified chinese, thanks, i appreciate it!
You can easily translate the app in the [Crowdin page](https://crwd.in/birday) of the project. Just select simplified chinese and translate how many sentences you want. Of course, you will be credited 😄

**Comment by ghoevil** [comment]
@m-i-n-a-r ok tks! But the site cannot be opened from china, don't know why. Can you send the link inside your github?

**Comment by m-i-n-a-r** [comment]
You can find the file containing the strings in this project, and there's a guide in the Wiki to correctly translate the app, read it if you want!

**Comment by DominikNovosel** [comment]
You can still attempt to access Crowdin using a VPN, I use https://riseup.net/en/vpn because it's fuss-free and donation supported. I'm not sure why you cannot open it, it doesn't seem to be blocked.
