### ISSUE TITLE
New Widget Upcoming Events Visibility

### ISSUE THREAD

**Issue by s1w2a3** [m-i-n-a-r/birday#206]
Hi,
First, thank you very much for your work, I love your app!
The new widget is gorgeous, but it's got a flaw: upcoming events (below next birthday) are visible even if there's very little space to show them. This means that below the name of the next person whose birthday it is next, there's a grey and scrollable bar, which is actually the bubble that contains the upcoming events when the widget is bigger.

This might have been seen as as design element, but the scroll indicator from Android (which is on the right of the screen and shows scroll progress) is temporary visible when unlocking the phone or going on the home screen, then disappear (see the screenshots).

![TijPpDr2m9](https://user-images.githubusercontent.com/68775901/203871876-19b7d237-ea68-4ff9-9668-d3bcf148cf16.png)
![gIYXej28WM](https://user-images.githubusercontent.com/68775901/203871875-9dc4c0c4-c76d-4500-9746-3a676faa771c.png)

I think only the next birthday should be seen in this widget size.

Thank you!

**Comment by m-i-n-a-r** [comment]
The list visibility depends on a lot of factors: text size, screen size and density, size of the widget itself (on my launcher, Niagara, i can resize it freely to any size). The list is always shown to make the widget flexible and avoid multiple configurations. For instance, if you had a longer name or multiple events, such as you had 3 lines of text, the list would have been hidden. I understand your point though. I'll probably add a configuration screen, just like the other old widget, with an option to completely hide the list and other customization settings. 😄

**Comment by s1w2a3** [comment]
Okay, thank you! On Pixel Launcher (which I'm using), you can't resize freely a widget so these settings would be very useful.
