### ISSUE TITLE
Support for older devices

### ISSUE THREAD

**Issue by mauricioeluri** [m-i-n-a-r/birday#21]
I dont know if the programming language and effects you use are compatible with older android versions, but i would love to try your app if you add support for older versions as well :D

**Comment by m-i-n-a-r** [comment]
Birday currently supports Android 8.0 and up. To support Android 6 or 7, the app requires huge modifications since i use the latest Android features and some of them are not available on previous versions. What version are you using now?

**Comment by mauricioeluri** [comment]
5.1. No problem :)
