### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by xmha97** [m-i-n-a-r/birday#210]
Why the navigation bar is dark on the light theme?

![Screenshot_2022-11-26-00-04-37-366_com.minar.birday.jpg](https://user-images.githubusercontent.com/23485114/204053100-b9c9b92b-022a-4ab5-b1b3-92e57ea75d0f.jpg)

Please fix this issue.

**Comment by m-i-n-a-r** [comment]
That's a design choice, the navbar is grey since the very first version of Birday. I'll consider a restyle in future updates 👍
