### ISSUE TITLE
Labeled contacts do not get imported

### ISSUE THREAD

**Issue by profitrollgame** [m-i-n-a-r/birday#216]
So basically yeah, exactly as the title says – all contacts that have a lable on them simply do not get imported. I'm using Google Contacts app to edit them. Applies to both Google-saved and DAVx5 synced contacts. I'm using version `4.1.0` from FDroid on DotOS (Android 11). Google Contacts version `3.81.23.488847150`.

![Screenshot_20221206-235214_Contacts~2](https://user-images.githubusercontent.com/47523801/206042148-9fb01b97-8bc6-4ceb-b1f3-3cfd373c85bd.png)

**Comment by m-i-n-a-r** [comment]
Hi and thanks for letting me know! I'm already investigating this issue and i didn't find a fix yet, but I modified the import procedure to also import contacts with middle names, prefix etc in v4.x and i probably did something wrong 🤔

**Comment by profitrollgame** [comment]
Hm. I tried a few more times and now can say, that contacts in Google with labels get fetched okay, however those synced with CalDAV only seem to sync when completely without any labels. Here's what I got. After exporting both Google and CalDAV contacts I don't see any labels in it, so those are only stored on local machine. Idk how this indexing works actually...
![Screenshot_20221207-002723_Contacts~2](https://user-images.githubusercontent.com/47523801/206048155-1d8e875b-1e84-4e67-b631-10f7d55fae79.png)
![Screenshot_20221207-002728_Contacts~2](https://user-images.githubusercontent.com/47523801/206048163-feb55671-a7ed-4ede-bd95-a52e70aa11f6.png)
![Screenshot_20221207-002501_Birday~2](https://user-images.githubusercontent.com/47523801/206048167-5deeee7b-e3e5-42eb-954c-f38a4839536b.png)

**Comment by m-i-n-a-r** [comment]
Thanks for the additional information, I should be able to recreate the issue. I've no idea what's wrong since Birday only tries to find contacts containing events, but for some reason the query discards some contacts. A similar issue is #208

**Comment by m-i-n-a-r** [comment]
Just released in the Play Store Beta channel (and here and on F-Droid in a few days)! I'll close this and other similar issues, but feel free to reopen it if this bug persists.
