### ISSUE TITLE
birthdays cannot be imported from contacts

### ISSUE THREAD

**Issue by evilsh3ll** [m-i-n-a-r/birday#224]
Hello I've a one plus 8t (Kebab) with custom rom crDroid 7.14 (android 11), and I have google services.
Birthdays are added in contacts using Simple Contacts Pro (installed from f-droid). I installed birday from f-droid (to be precise, using NeoStore). I used your application Birday without problems for months (maybe >year), this is the first time that it can't import birthdays.
I tried to:
- remove/reinstall Birday
- give it the access to contacts
- manually import birthdays by using the function "import events from contacts" (in Birday settings), the output message is: "No event found!"

Additional info:
- I'm sure all birthdays are saved in the contacts because: i never modified them for months, they were imported without problems months ago, other applications can extract/read them (simple calendar pro from f-droid for example)
- my contacts don't have tags
- contacts are save in internal memory (not sim), as always, they never changed location in the past
- I don't use any other contacts application other than simple contacts pro and the android stock "call/contacts" app. I don't have any app disabled or hidden
![1](https://user-images.githubusercontent.com/63223659/212396987-05948681-3bf3-457d-98e0-bd03fbed5d11.jpg)
![2](https://user-images.githubusercontent.com/63223659/212396991-50f72d32-c510-4be0-ac52-634488517874.jpg)
![3](https://user-images.githubusercontent.com/63223659/212396993-e5e46ff5-9844-4c52-a048-bcb0a4dcae69.jpg)

**Comment by pudup** [comment]
Had same issue after reinstall
Uninstalled and installed version 3.1.1 and imported and then updated to newest

**Comment by evilsh3ll** [comment]
> Had same issue after reinstall Uninstalled and installed version 3.1.1 and imported and then updated to newest
it worked but the problem is still present, I'll not update the application 3.1.1 until the bug is fixed

**Comment by pudup** [comment]
Yeah I should've mentioned, it doesn't fix it if you go back to the latest version

**Comment by m-i-n-a-r** [comment]
I'm working on it. Still, i have no idea what's wrong. I changed the import process to also import contacts with middle names, name prefix and suffix, and that's it. Can you send me an email? I need a tester to make sure the bug is fixed before releasing the next update!

**Comment by m-i-n-a-r** [comment]
@evilsh3ll @pudup i recreated the same exact setup, and i'm quite sure it's not Birday fault. Simple contacts can both save a contact (and his/her events) in an account, in the contacts provider on in the device memory. In the latter case, the contact is *NOT* visible to any external application. So, Birday can't detect it. Does it make sense to you?

**Comment by pudup** [comment]
> @evilsh3ll @pudup i recreated the same exact setup, and i'm quite sure it's not Birday fault. Simple contacts can both save a contact (and his/her events) in an account, in the contacts provider on in the device memory. In the latter case, the contact is _NOT_ visible to any external application. So, Birday can't detect it. Does it make sense to you?

All my contacts are saved to a decsync account and not on device storage. All I can say is that 3.1.1 succeeds in importing birthdays with no other changes.

**Comment by m-i-n-a-r** [comment]
Ok, so your case if different. As i said, i rewrote the import strategy to also include name prefix, suffix and nickname in v4.x. And, seems like I broke something. The weird fact is that i'm trying to recreate the problem on my test devices and I'm not succeeding, unless i save the event in device storage, as mentioned above. And a very small amount of users had this bug with totally different devices, android versions, apps and setups. And that's driving me nuts :D

Could you tell me every possible detail on your setup? Anything could be important at this point. This bug is literaly the last thing to fix before releasing v4.2.0!

**Comment by pudup** [comment]
My own setup might be a bit unique. It's android 12, near stock like, motorola, not custom ROM. 
But most of the built in system apps have been removed. Deleted from system partition. That includes the stock contacts app, which wuz Google contacts iirc. 
Contacts provider (contact storage) however is not removed. 

My contacts app is Simple Contacts and it uses a decsync account. 
Every single app that requires contacts can see all my contacts. That includes Whatsapp, Signal, Telegram, Conversations and 2 dialer apps(simple dialer, which I'm not using cuz it's bugged, and lineageOS stock android 11 dialer which is the replacement till simple dialer is fixed). 3.1.1 works fine, but the latest says "No Events Found". It has all permissions granted.

**Comment by m-i-n-a-r** [comment]
OK, i have a possible fix. I'll publish a beta soon. @pudup and @evilsh3ll, if you didn't install the app from the Play Store, here's an unsigned version to test. Please let me know if it works or if you see any debug message while you try to import contacts. 
[Birday420Debug.zip](https://github.com/m-i-n-a-r/birday/files/10744153/Birday420Debug.zip) Side note: you will have to uninstall the current version to test this one, so make sure to perform a backup first. Thanks!

**Comment by pudup** [comment]
It works for me

**Comment by m-i-n-a-r** [comment]
Nice to hear that! Thanks for taking the time to test! I'll close this and other similar issues when the new version is released.  😄

**Comment by pudup** [comment]
Thanks for the great app :>

**Comment by m-i-n-a-r** [comment]
@MatsG23 Thanks for confirming! I should release it in the Google Play Beta program, but you can expect a release on Github and F-Droid shortly after 😄

**Comment by m-i-n-a-r** [comment]
Just released in the Play Store Beta channel (and here and on F-Droid in a few days)! I'll close this and other similar issues, but feel free to reopen it if this bug persists.

**Comment by Lovro1107** [comment]
Hello! I just found your app and have this issue of events not being imported from contacts.
I have the latest app version 4.3.0 running on GrapheneOS and using SimpleContacts.

I have this phone for about two months and didn't add any birthdays on it. I imported all my contacts from the previous phone (also using SimpleContacts). I think the bug has something to do with contacts being imported, because I added a birthday to a contact on my phone now (for test) and that event then showed up when importing from contacts.

**Comment by m-i-n-a-r** [comment]
so, to summarize:
you have X contacts, and you import them into yout new phone, in simplecontacts
those X contacts have birthdays and events set
you try to import them in Birday, and Birday finds nothing (or crashes??)
if you enter a birthday manually, Birday finds it

Is that correct?

**Comment by Lovro1107** [comment]
Yes, that is correct. Birday doesn't find anything, did not crash.

And just to clarify: I can add an event to the existing imported contact and that event is then detected by Birday. I don't need to add a new contact.

**Comment by MrFredber** [comment]
Same issue on Realme 11 Pro+ on ColorOS 5
App version 4.5.1
![IMG_20241118_103520.jpg](https://github.com/user-attachments/assets/560df83f-b85d-46a4-b059-56748ba6878d)

![Screenshot_2024-11-18-10-35-33-90_f4ae6d729839174ed6cd6032a3d1b265.jpg](https://github.com/user-attachments/assets/ee1f2d98-8530-475c-b952-8ee3c3fcdd98)
