### ISSUE TITLE
Chinese year calculation should take into account full date

### ISSUE THREAD

**Issue by koterpillar** [m-i-n-a-r/birday#23]
Years in Chinese lunar calendar ("Chinese zodiac") don't start on January 1. For example, year of the Rat started on January 25, 2020, and therefore someone born on January 10 would still be an Ox.

Birday should implement the lunar calendar properly and show the correct signs.

I've found:

* Official [ChineseCalendar](https://developer.android.com/reference/kotlin/android/icu/util/ChineseCalendar) class. Unfortunately I can't find how to convert Gregorian dates to this.
* [Time4A](https://github.com/MenoData/Time4A) ([introduction](http://www.time4j.net/tutorial/introduction.html)), which includes its own [ChineseCalendar](http://time4j.net/javadoc-en/net/time4j/calendar/ChineseCalendar.html) implementation. This is an extra dependency but seems easier to work with.

**Comment by m-i-n-a-r** [comment]
Yep, i used an approximation and i forgot to fix it, since it is a bit complicated. I'll look into it as soon as possible, thanks 👍
