### ISSUE TITLE
Multiple additional notifications

### ISSUE THREAD

**Issue by Grommanos** [m-i-n-a-r/birday#238]
Hi, I like your app.
But I'm missing a feature where you can set multiple notifications for birthday reminders.

A nice option would be to allow that by changing these radio buttons to checkboxes:

![4ff7df82-c21b-4262-ad72-4a4a77f26535](https://user-images.githubusercontent.com/64316901/220433763-9b614239-b27d-4d69-ba8e-c39b2fd4c77b.jpg)

Thanks and regards.

**Comment by m-i-n-a-r** [comment]
It looks easy, but believe it or not it requires a lot of changes and work, so i decided to keep things as they are in the update i just released. I'll see what i can do in future releases though, especially if this issue is commented by other users! 😄

**Comment by Darkempire78** [comment]
It's a good idea!

**Comment by mikulik86** [comment]
I also miss more notifications.
Grommanos's suggestion would be one way. Or I would be perfectly fine with an aditional setting that would enable notification on every day between the selected day before the event and the event day.

**Comment by m-i-n-a-r** [comment]
Ok then, I'll see what I can do 🙂

**Comment by trymeouteh** [comment]
I would like this also.

**Comment by herrbrixter** [comment]
I also like this change. I used another birthday app and I selected 3 options:

Remind me 1 week before, 1 day before, and on the day itself.

**Comment by m-i-n-a-r** [comment]
I'm working on it now, it will take time since it's longer than expected, but I'm working on it, finally.

**Comment by m-i-n-a-r** [comment]
Done in 431b196b298bd761a03f2a01fef7e2b3456f8786 and available in next release. The only downside is that the additional notification setting will be cleared, so if you previously had an additional notification, you have to enable it again from the new multi-selection option. I'll write a big disclaimer in the changelog that nobody will read 😄
