### ISSUE TITLE
"Old" widget no longer working

### ISSUE THREAD

**Issue by bovergaauw** [m-i-n-a-r/birday#239]
When I add an "old"-style wigdet in version 4.2.0, I get a box displaying "Problem loading widget"

**Comment by m-i-n-a-r** [comment]
Well well, that's weird. I tested it on many devices. Thanks for letting me know! I need more details, like:
- Your device (and, is it rooted?)
- Your Android version
- Your launcher
- How many events did you save? 
- Which settings are you using for the widget? 

Thanks in advance!

**Comment by bovergaauw** [comment]
Hi,
I'm using Birday on an un-rooted Samsung Galaxy S9 with Android 10 and Samsung One UI 2.5. I tested the widget:
- after upgrading to version 4.2.0
- after having backed up the database, uninstalled and reinstalled the app(i.e. with an empty database)
- after having imported my backup.
I think my database contains around 50 to 60 events, and tried various widget settings.
In all cases I had the same error message.
Hope this helps.
In any case, thanks for all your efforts!

**Comment by m-i-n-a-r** [comment]
Ok, after further investigation i can confirm that for no apparent reasont the minimal widget broke on Android 10, 9 and 8. My bad,  i only tested it in 11, 12 and 13. I'm already working on a quick fix, i should release a new update in more or less a week!

**Comment by m-i-n-a-r** [comment]
Issue found and fixed in 224ade8c87cd6ba684ee95c1a4cdfcbeea061675 , the fix should be available in the next release. Thanks for letting me know!
