### ISSUE TITLE
Latest version not on F-Droid

### ISSUE THREAD

**Issue by bovergaauw** [m-i-n-a-r/birday#248]
The latest version, 4.3.0, is not available on F-Droid. Is that a issue with F-Droid or with Birday?

**Comment by m-i-n-a-r** [comment]
It should be an F-droid problem, since i created a new release and updated the repository accordingly. I'll let you know if i found out more!

**Comment by Yoanndp** [comment]
> It should be an F-droid problem, since i created a new release and updated the repository accordingly. I'll let you know if i found out more!

Hello, it's still not there. Can you please fix it ?

**Comment by kajdo** [comment]
also waiting hard for the update because of the widget issue ... but my understanding is that the dev can't do too much if f-droid isn't updating

maybe a individual repo would help which we can include in f-droid?

**Comment by kajdo** [comment]
confirm ... got the update 

really graet work, the problem with the widget is gone
