### ISSUE TITLE
Improvements on the date input

### ISSUE THREAD

**Issue by Nesaijn** [m-i-n-a-r/birday#25]
I have found some ways to further improve the user experience.
1. When the birth year is not included then it would look nicer in the input field if it would also not been shown there. In short: remove year in date input field if year is not being considered.
2. You can't move forward to the future in the calendar. If you could, this would make it easier to select for example the next month and then pick a year. Or if the year is not being considered, then it is kind of a hassle to pick the last year just so you can pick a month which is further than the current one.

Other than that, I think the app really looks good! Good job!

**Comment by m-i-n-a-r** [comment]
Yep, i agree, but I didn't do it to avoid bugs and weird behaviors. I'll see what I can do in future updates though!

**Comment by m-i-n-a-r** [comment]
I improved the date selection in d576ccd2ac1b3f29290c76292db532b984857a55 : now the user can select any date in the current year, and if the date is after today, the year will be fixed automatically after the selection 👍 I could improve it further, but i'll close this issue in the meantime 😄
