### ISSUE TITLE
[FEATURE REQUEST] "Show only favorites" widget option

### ISSUE THREAD

**Issue by yglukhov** [m-i-n-a-r/birday#250]
Thank you for this very useful app!

Subj. Would be great to setup widget to behave as if non-favorite items do not exists.

**Comment by m-i-n-a-r** [comment]
I was sure this feature was already available, but i was wrong 😄 added to the todo list for the next release!

**Comment by m-i-n-a-r** [comment]
I forgot this, and I have no idea why, sorry! I'll add it in the next beta, I promise 😿

**Comment by m-i-n-a-r** [comment]
And I finally remembered to do it, It's available in the latest beta 😄
