### ISSUE TITLE
info request: what should deaths be labeled as?

### ISSUE THREAD

**Issue by nutpantz** [m-i-n-a-r/birday#251]
None of my contacts with the custom label "death" are ever imported with my contacts.
What should the custom label be?

"Anniversary" and "birthdate" work fine.

**Comment by m-i-n-a-r** [comment]
The import procedure supports the event types supported in the Contacts app, and death anniversary isn't a supported event type in the contacts app. This means that any custom labelled event will be imported with the type "other". If the events labeled "death" aren't imported at all, that's an issue 😄
