### ISSUE TITLE
Can't add any widget to my launcher

### ISSUE THREAD

**Issue by Marmous** [m-i-n-a-r/birday#256]
Hi ! It's been several months (since the new widget was introduced I guess) that I can't add any Birday widget to my launcher. There is no Birday item in my widget list.

I am using this device:
- Model: Hisense A5 (HLTE202N)
- Rooted: yes
- Launcher : Vision 7
- Android version: 9

Best regards,

Marmous

**Comment by m-i-n-a-r** [comment]
Can you try to use another launcher first? I have a test Android 9 device and i can see the widgets just fine 🤔

**Comment by Marmous** [comment]
It does work with [this launcher](https://github.com/SimpleMobileTools/Simple-Launcher) found on f-droid.

**Comment by m-i-n-a-r** [comment]
Well, in such case I guess it's a launcher side issue. I tried using both nova, samsung launcher and niagara on Android 9 and I can add the widgets just fine. I'll close this, but feel free to reopen if you think I'm wrong 😄
