### ISSUE TITLE
UI Language issue

### ISSUE THREAD

**Issue by VasilisKos** [m-i-n-a-r/birday#258]
Though the app appears to be fully translated into Greek in Crowdin, when I installed it from Play, it was displayed in English. Why is that? Never had this issue with any other app in the past.
Using a Nokia 6.2, on stock Android 11.

**Comment by m-i-n-a-r** [comment]
Seems like there's some resource related problem for greek 😕 I'm sorry for the inconvenience, I'll try to fix it asap!

**Comment by m-i-n-a-r** [comment]
Fixed! As mentioned in another issue, I should release an update in a couple weeks 😄
