### ISSUE TITLE
Add Viber in Quick Apps

### ISSUE THREAD

**Issue by VasilisKos** [m-i-n-a-r/birday#260]
Please add Viber in the list of available quick apps, when tapping on the upcoming birthday. It's one of the most popular apps worldwide, with more than a billion installs.

**Comment by m-i-n-a-r** [comment]
I'll see what i can do, I'll probably change the quick apps screen to only display the installed apps, between the available. Thanks for the advice though!

**Comment by m-i-n-a-r** [comment]
Done. I also improved how quick apps are displayed. I'll release an update in a couple weeks, more or less!
