### ISSUE TITLE
Custom Event

### ISSUE THREAD

**Issue by Aditya137x** [m-i-n-a-r/birday#263]
There are several event type and instead of selecting others for all of them it would be nice to have the ability to add Custom event types.

**Comment by m-i-n-a-r** [comment]
I considered this, but for how the app is built it would require a complete refactor and a lot of work. Instead, if requested, i can add specific event types. The most common event types should already be in the app, but i accept any suggestion. I'll close this, but feel free to reopen to suggest a specific new event type 😄
