### ISSUE TITLE
Ask for their birthdays!!!

### ISSUE THREAD

**Issue by saikrishna130** [m-i-n-a-r/birday#264]
Can we have a feature where I can ask all my contacts to provide thier birthdays and when they provide a date it lands in my birday app DB. It will help my time to ask and save each person's birthday.

**Comment by m-i-n-a-r** [comment]
It surely would be helpful, but how could i do that? I mean, the only way is to share events from Birday to Birday. For example, i have my birthday saved in mi Birday app, i tap on "share" and i can send you some kind of link, string or qr you can quickly open using Birday itself to import my birthday. And there's already an issue for this, #173 
If you have suggestions, you can add them on the original issue, but I'm already working on something similar. It will take time though 😄
