### ISSUE TITLE
[FEATURE REQUEST] - Early Emails

### ISSUE THREAD

**Issue by EcceMaterTua** [m-i-n-a-r/birday#265]
Could you add a feature to send me an email at a designated date/time before a person's birthday? For example, if a person's birthday is on June 30th, I'd like to receive an email on June 23rd or June 15th or something saying, "Pedro's birthday is on June 30th" or something like that.

That way, I'd have enough time to get a gift or card. Thanks for this great app!

**Comment by m-i-n-a-r** [comment]
This feature would require a backend, a server to run it and additional permissions, so I'm not gonna lie, I can't implement it. All I can do is improve and expand the native notification feature!
