### ISSUE TITLE
Upcoming birth day in details?

### ISSUE THREAD

**Issue by 13thThief** [m-i-n-a-r/birday#266]
Hi, thanks for making Birday! I love everything about it. There is one thing– when I click on a person for more details, I can see "X days left". It would be great if we know what day actually the birthday is falling on, like "X days left, on Friday".

Thanks once again!

**Comment by m-i-n-a-r** [comment]
Hi and sorry for the late reply! Yep, I can do this. I'll add it to the todo list 😄
