### ISSUE TITLE
Februar is shown as March

### ISSUE THREAD

**Issue by Nesaijn** [m-i-n-a-r/birday#27]
On the German locale, when want to choose a month in the month picker the name of the month of March is also shown for Februar. When I press on it, it shows Februar though.
When Februar is choosen, everything works fine. If not, March is shown as the month name.
How it is ("Februar" unselected):
![photo_2020-10-30_20-19-20](https://user-images.githubusercontent.com/25134837/97750422-0a77dc80-1af1-11eb-8cf4-58a6a8f69374.jpg)

How it should be ("Februar" selected):
![photo_2020-10-30_20-44-29](https://user-images.githubusercontent.com/25134837/97750428-0c41a000-1af1-11eb-97c9-2a1440e7b2a2.jpg)

Xperia XA2
LineageOS 17.1 (Android 10)

**Comment by simonesestito** [comment]
I think you should report the bug on the date picker library repository instead of this one, since this app only uses the lib but has no control over it, as far as I know

**Comment by m-i-n-a-r** [comment]
Yep, i agree. It's probably a library fault, and sadly the developers seems inactive at the moment. Try to open an issue here: https://github.com/afollestad/material-dialogs/issues/

**Comment by Nesaijn** [comment]
What library version of material dialogs is being used in birday?

**Comment by m-i-n-a-r** [comment]
3.1, since the latest version has a bug you can find here https://github.com/afollestad/material-dialogs/issues/1957
