### ISSUE TITLE
Fix wrong traductions from english to spanish 

### ISSUE THREAD

**Issue by CarlosTaipe** [m-i-n-a-r/birday#270]
Hello, when reviewing the Spanish translations, I have seen some errors and I can correct them, but I have a doubt.

Birthday in Spanish is Cumpleaños, for this reason the name of the app is Cumpleaños, the title in the onboarding is "Bienvenido/a a Cumpleaños" and some  other descriptions, for this reason I want to know if in the Spanish translations we will use Birthday or Cumpleaños.

I am waiting for your answer to start the corrections

P.S.: I am a native Spanish speaker (my Spanish is Latin American).

**Comment by m-i-n-a-r** [comment]
Well that's entirely wrong and i probably did miss it. The name of the app is "Birday" and since it's a name, it shouldn't be translated at all, so for your example, it should be "Bienvenido/a a Birday". Thanks for the help!
