### ISSUE TITLE
Favorites gets cleared

### ISSUE THREAD

**Issue by bohaoy** [m-i-n-a-r/birday#279]
I am unable to reproduce this bug with a systematic way, but when I add events into the favorite page they disappear after not using the application for a while. This has happened to me in multiple occasions within an hour.

**Comment by bohaoy** [comment]
I'm going to see if turning off the experimental `Auto import on launch` would affect anything

**Comment by bohaoy** [comment]
It seems that the auto import from the experiments feature clears the favorites

**Comment by m-i-n-a-r** [comment]
Thanks for letting me know. I'll try to keep the favorite state even if an imported event is replacing a previously inserted evend (this is what happens everytime the auto-import is executed).

**Comment by para2ox** [comment]
I've faced the same problem. It would be great if this could be fixed, because auto import is a useful feature.

**Comment by m-i-n-a-r** [comment]
I should work on it after the next update, I'll update the issue as soon as i start working on it!

**Comment by m-i-n-a-r** [comment]
Ok, the update I just released in beta contains an option to avoid overwriting existing events when importing, try enabling it and the issue should be fixed!
