### ISSUE TITLE
Crash when importing Birday backup from Nextcloud

### ISSUE THREAD

**Issue by kaibagley** [m-i-n-a-r/birday#282]
Hey, thanks for the wonderful app!

When importing a birday backup, my app closes and nothing is imported. Please let me know if you need more info!

**Comment by m-i-n-a-r** [comment]
Sorry for the super late reply, but yes, any detail is well appreciated since it works properly on my test devices. Thanks!

**Comment by kaibagley** [comment]
Oops I mustn't have been paying attention when I made this issue, the crash only occurs when using a backup stored on Nextcloud. When copying this to local storage the backup works fine.

Since I store my backups on my Nextcloud, is there any hope of backing up from a file stored on NC?

**Comment by m-i-n-a-r** [comment]
It's probably a permission/nextcloud app related problem, I think it's out of my control. I'll investigate, but since I'm quite sure there's nothing I can to, I'll close this issue for now :)
