### ISSUE TITLE
Date picker should default to current day

### ISSUE THREAD

**Issue by herrbrixter** [m-i-n-a-r/birday#297]
When I add a new birthday and insert the day, the date picker shows up. However, the default date is yesterday's date. It's a weird behavior. Normally, in other applications, the default date is always the current day.

**Comment by m-i-n-a-r** [comment]
No problem, I'll change that. I don't even remember why I chose to select yesterday instead of today, to be honest.

**Comment by DominikNovosel** [comment]
> I don't even remember why I chose to select yesterday instead of today, to be honest.

I remember: #170

**Comment by m-i-n-a-r** [comment]
Done in 54ef9f41f74ae4a1e76aa6417c2513e1a3e3e2b8 😄 
@DominikNovosel the issue you mentioned should be a different case, namely the insertion of an event one day in the future. This should still work!
