### ISSUE TITLE
Right align additional notification setting

### ISSUE THREAD

**Issue by herrbrixter** [m-i-n-a-r/birday#298]
In the setting for additional notification, the answer directly follows the setting description. For example:

Send an additional notification days before the event. One day before.

The answer should be right aligned so it is clear that it is the selected setting

Send an additional notification days before the event. <-------------space--------------->One day before.

**Comment by m-i-n-a-r** [comment]
I agree this would improve the readability, but it's against the Material Design guidelines and most importantly, The "send an additional notification days.. etc" is a single string, you can easily see it in Crowdin. For this reason, put a dynamic space in a single string it basically impossible. So, sadly, that's not possible 😞

**Comment by herrbrixter** [comment]
Maybe change the period to a semi-colon so "One day before" looks like the setting that the user chose.

Send an additional notification days before the event: One day before

**Comment by m-i-n-a-r** [comment]
Ok, I can do this. Also, I changed that option to make it a multi selection, and this means that 10 options could be selected at the same time, so I'm not sure how to handle this 😕

**Comment by m-i-n-a-r** [comment]
You don't see it because I didn't release it yet 😄 I have a couple more features to finish, then I'll release the update in the beta channel, and after a week or so I'll release it in the stable channel and on F-Droid! That's a long process, but I did a lot of work on the app and I have to make sure it works as expected 😅

**Comment by herrbrixter** [comment]
No problem. I'm not rushing. Take your time.
