### ISSUE TITLE
Don't group similar notifications

### ISSUE THREAD

**Issue by herrbrixter** [m-i-n-a-r/birday#299]
Please add an option to send individual notifications, instead of grouped notification, so I can act on them individually.

For example, Bob and Joe's birthday are today. I want 2 individual notifications.

Bob's birthday is today

Joe's birthday is today

Then I can greet Bob happy birthday then dismiss Bob's notification. Joe's notification remains. Then I will call Joe next, then dismiss Joe's notification.

Another use is if I want to ignore one of them. Let's say Joe is not a close friend. I could just dismiss Joe's notification while Bob's remains.

If the notifications are grouped, I can't use the notification as separate reminders.

**Comment by m-i-n-a-r** [comment]
Done in 77a09455cbafd3d20e0ba0aa4669f44ba34b9173 the option will be available in the experimental settings until it gets properly translated and tested, but it should work as expected 😄
