### ISSUE TITLE
custom text setup for widget enhancement

### ISSUE THREAD

**Issue by Meibes** [m-i-n-a-r/birday#30]
Hi,
thanks for the great app it really looks good. It would be nice if the user could change the text setup for the widget. Right now it's like:

```
icon "upcoming birthdays"
<name>, <day in number> <month in text> <year>. <number> "remaining days"
```

for a minimalist like me, I don't need the icon or the text "upcoming birthdays" because it just takes up space I could use for useful information. what really bothers me is that there is two times information regarding the time being the exact date and the remaining days. if I could choose which text is displayed I would pick something like:
`
<name (maybe even full name)> is turning <number> in <number> days`

this way you have the information how old someone turns and the remaining time until he/she does. so I don't have to open the app and check how old he/she gets or even calculate the age myself. getting more useful information with less text.

also it would be nice to see the next 2-3 birthdays and not just one (?). that is also a reason why it would be okay for me to drop the icon and "upcoming birthdays" and add the favourite icons before the contacts or something, so I see in an instant that one of my favourites is getting older soon

cheers

**Comment by m-i-n-a-r** [comment]
Hi and sorry for the late reply. I agree with you that the upper text is quite useless, and i was thinking of a widget redesign too. The reason i didn't put a "name is turning number in days" format is because many languages have different translations of this sentence and the data are positioned differently. I'll try to optimized the text though, thanks for the suggestion!

**Comment by m-i-n-a-r** [comment]
The widget will be completely redesigned in the next update, so i'll close any widget related issue for now. I hope to complete the redesign in one month, more or less.
