### ISSUE TITLE
Widget with the next two events, instead of one

### ISSUE THREAD

**Issue by pick-and-mix** [m-i-n-a-r/birday#301]
Love the app, I have just set it all up.

Would it be possible to have a widget with the next two events, instead of one?
So instead of 3x1 having 3x2 widget.
I have a few months when there is a birthday within a few days of each other.
A reminder for both would help.

**Comment by m-i-n-a-r** [comment]
Well the list widget can display a list with the next events, but I understand it can take too much space. I'll try to add a widget option to show another row with the "second next event" in it!

**Comment by m-i-n-a-r** [comment]
Done in 665a35048e5a339f16c95cadafb337af9050e9d3 and following commit. It should be available as a widget option in the next release (hopefully soon)
