### ISSUE TITLE
[feature request] auto backup or webdav support

### ISSUE THREAD

**Issue by du33169** [m-i-n-a-r/birday#302]
I installed birday from F-Droid so there is no google cloud back up. Currently I have to manually click "export and share event" and then upload after editing. Is there any plan to add auto backup or webdav support?
I am aware that this app is kind of private so some may not want to give it network access. Another posible way is to let user decide where to save the backup files so that we can save it to a webdav drive through SAF(Storage Access Framework), using apps like [davx5](https://github.com/bitfireAT/davx5-ose).

**Comment by Nordlicht-13** [comment]
Maybe it could be a way to store the entries in a calendar that can be synced to a cloud.

https://github.com/m-i-n-a-r/birday/issues/295

**Comment by m-i-n-a-r** [comment]
When installed from Play Store, the app has the automatic Google backup, but of course, it doesn't work in the F-Droid version. That's a fairly complex feature to implement, I'm not gonna lie, but I can try to create an "export to calendar" feature. I'll let you know when I start working on it!

**Comment by faan11** [comment]
Hi, i think that these events can be sync with a caldav/carddav server like radicale

**Comment by faan11** [comment]
Hi @m-i-n-a-r , are there are any ETA for this feature?

**Comment by m-i-n-a-r** [comment]
I did some research, but, basically, I need help. I have no idea how to implement such a thing while keeping the app simple and straightforward.

**Comment by faan11** [comment]
I think i have an idea that might solve this issue. This might be a workaround but it shouldn't be hard to implement it.
The idea is to sync the events with the Android calendar. An external tool such as [Davx5](https://www.davx5.com/) can be used to sync the android calendar to a Webdav server.
Birday needs a sync function that merges the events from the Android calendar with the Birday events. The function can use the event name to avoid duplicates.
This sync can be done in background or can be triggered using a button. 
The application already has an import function. It should be feasible. What do you think?

**Comment by m-i-n-a-r** [comment]
Ok, it makes sense and I'll take a look! I could simply add an "export to calendar" function, it should do the trick.

**Comment by du33169** [comment]
Hi! It looks like you are struggling with the feature "export to calendar". It's a good one but not exactly what I described in this issue. It might be simpler in this way, than dealing with any calendar stuff:
1. Add a preference item to let the user select the output path of the exported backup file. This shouldn't be hard because birday already has support for exporting to a fixed path, currently `Android/data/com.minar.birday/files`. You don't need any file permission if you use SAF and `ACTION_OPEN_DOCUMENT_TREE`.
2. Add a hook function invoking the export process after the user submits any changes. This can be provided as a preference item as well.

Thank you again for this fantastic application!

**Comment by m-i-n-a-r** [comment]
Yep, this is an automatica backup feature and it was requested, I'll work on it as well, but I'm also trying to add an export to calendar feature (there's another issue requesting it) so they are two different features. I'll try to implement both in the next udpate 😄

**Comment by m-i-n-a-r** [comment]
So, the upcoming beta has both the auto backup and the export to calendar feature, so I think I can close this, right? 😄
