### ISSUE TITLE
Why the restriction on numbers and symbols in names?

### ISSUE THREAD

**Issue by Commenter25** [m-i-n-a-r/birday#31]
This seems like a pointless restriction to me. If it makes the app run faster or work better, then that makes more sense. But otherwise, why have the app work against the user for no benefit? Yeah, you don't usually see people in the real world with numbers or symbols in their name, but what if I want to put someone's online username? What if I wanna put a little heart next to my partner's name?

**Comment by m-i-n-a-r** [comment]
Well, i put the restriction to only encourage the user to write proper names and have a clean database, but you're right. I could allow emoji and numbers at least. I'll se what i can do!

**Comment by m-i-n-a-r** [comment]
in [this](bc4c2f0e51085d4f510c0579fe9ed47ade36702c) commit i allowed the emojis in both first name and last name. Regarding numbers, i prefer to avoid them for now 👍 thanks again for the suggestion!
