### ISSUE TITLE
Overview screen contains incorrect month names in Croatian

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#311]
![Screenshot_20240423_160839_Birday.jpg](https://github.com/m-i-n-a-r/birday/assets/66269443/0c0d17d9-ef74-4fbe-ad41-734ddf8149af)

In Croatian, we have these things called cases, or padeži. To cut a long story short, the overview screen uses the genitive form of month names, which is normally used after ordinal numbers, eg. 15. siječnja to signify the 15th of January. When simply naming the months, you use the nominative form: siječanj, veljača, ožujak, etc. Since these names aren't part of the strings.xml file, I presume they are taken from the system locale, so I'm not sure how to fix this or whether other languages are affected.

**Comment by m-i-n-a-r** [comment]
Didn't know that! This depends on how the month names are taken, and specifically how I take them in the library I use, tasticalendar. So this is an issue of the library itself, to be precise. I'll investigate as soon as possible, thanks for letting me know! 👍

**Comment by DominikNovosel** [comment]
Neither did I, I literally discovered how to access the overview screen by accident some time ago. I was convinced it wasn't implemented yet. 😂

**Comment by m-i-n-a-r** [comment]
I opened an issue in the library itself, to keep things clean! https://github.com/m-i-n-a-r/tasticalendar/issues/4
