### ISSUE TITLE
feature request: human readable export

### ISSUE THREAD

**Issue by nutpantz** [m-i-n-a-r/birday#313]
i love backups and the best backup is a human readable file
like a text file with all the events listed.
maybe coma separated   CSV file

**Comment by m-i-n-a-r** [comment]
You already have both the JSON and csv export! And they should be readable without any problem :)

**Comment by nutpantz** [comment]
Readable? yes. without any problem? Not so much.
Csv is great if there was csv or spreadsheet app for Android. I have not found one yet short of Microsoft exec or libre office calc. Not a small install for either.
