### ISSUE TITLE
Hide year when not considered

### ISSUE THREAD

**Issue by herrbrixter** [m-i-n-a-r/birday#317]
When adding a new contact and birthday, the birthday always shows the year (ex. May 4, 2024) regardless of "Consider the year". Please hide the year if the user doesn't want it. Just display "May 4".

**Comment by m-i-n-a-r** [comment]
The purpose of "consider the year" is to don't consider the year for a specific event. You will still see it in the form, but it won't be visible in the list, in the details, in the top card and so on. So, I'm not sure I understood where the problem is 😕

**Comment by herrbrixter** [comment]
I want the year hidden in the entry form because it is confusing. Please see how it is implemented in another app.

![Screenshot_2024-06-11-06-51-33-276_com marcow birthdaylist](https://github.com/m-i-n-a-r/birday/assets/31651148/990a9e6d-9576-4ce6-b40f-e752de64c92c)

![Screenshot_2024-06-11-06-51-37-768_com marcow birthdaylist](https://github.com/m-i-n-a-r/birday/assets/31651148/42aecc7e-88b7-478e-a90a-15abb17e1e29)

**Comment by herrbrixter** [comment]
Similar to #25 

Requester also wants to hide the year in the input field if the year is not considered.
