### ISSUE TITLE
Keep yesterday's birthdays visible

### ISSUE THREAD

**Issue by herrbrixter** [m-i-n-a-r/birday#318]
Birthdays that are missed are automatically placed on the bottom of the list and hidden. If the birthday was just yesterday, you can still greet your friend a belated happy birthday. Now, you can't do that because these birthdays are way below the list.

How about keeping yesterday's birthdays still on top of the list? Make this optional.

**Comment by m-i-n-a-r** [comment]
Well, that's not a bad idea, but I'm not sure how to implement it properly in the UI. I'll see what I can do 😄

**Comment by herrbrixter** [comment]
That sounds good. Thanks!

**Comment by herrbrixter** [comment]
Will there be a setting to enable this feature? I guess this is off by default.

**Comment by m-i-n-a-r** [comment]
Nope, it's always enabled, since it's not invasive at all. Of course, this section is not displayed when there aren't events in the past 10 days.
