### ISSUE TITLE
Suggestion: set minimum widget height to 1 row instead of 2

### ISSUE THREAD

**Issue by The3Designer** [m-i-n-a-r/birday#32]
Hi!

I love your app, but there is one thing I'd like to see improved/changed. Currently, the minimum widget height is 2 rows, while the information shown (title/header and 1 upcoming birthday) should fit within a 1-row widget. Reducing the minimum widget height to 1 row would allow me to place some more shortcuts on my homescreen.

**Comment by The3Designer** [comment]
Here are some links that might help you implement this feature, if you choose to do so, of course ;)

- https://stackoverflow.com/questions/14357569/widget-minheight-72dp-gives-2-rows-of-height
- https://stackoverflow.com/questions/8101955/how-to-make-4x1-size-widget-on-android-homescreen
- https://stackoverflow.com/questions/8101955/how-to-make-4x1-size-widget-on-android-homescreen/11289215#11289215
- https://stackoverflow.com/questions/12465512/android-4x1-widget-size

**Comment by m-i-n-a-r** [comment]
Hi, and sorry for the late reply. I used the current height to avoid cut content, but I understand your point. I'll see what I can do in the next update!

**Comment by m-i-n-a-r** [comment]
Done in f7502dff4fcd706276148872109205ed0d9e7c5e now the minimum size should be 3x1. In the next updates iìll try to also improve the layout displaying different contents depending on the widget size

**Comment by The3Designer** [comment]
Thanks for lookig into this and implementing it! 👍🏻 
I'll check it out once the update becomes available on F-Droid.

**Comment by The3Designer** [comment]
I've updated the app yesterday from F-Droid, but the minimum widget size is still 3x2. I tried to restart the phone, clear Birday cache, restart phone through recovery and wipe the cache in there, but the minimum widget size is still 3x2. Running on Android 10 by the way.

**Comment by m-i-n-a-r** [comment]
![IMG_20210106_103030_220.jpg](https://user-images.githubusercontent.com/8942111/103752633-3be9b880-500a-11eb-9ab8-bbce8f407b9e.jpg) that's really weird, in my phone (Oneplus 7 pro) the size is correct. Maybe it depends on your screen size? I'll look into it, I'm sorry 😔

**Comment by The3Designer** [comment]
> 
> 
> ![IMG_20210106_103030_220.jpg](https://user-images.githubusercontent.com/8942111/103752633-3be9b880-500a-11eb-9ab8-bbce8f407b9e.jpg)
> 
> that's really weird, in my phone (Oneplus 7 pro) the size is correct. Maybe it depends on your screen size? I'll look into it, I'm sorry 😔

I fixed it! I set the "Smallest width" option in the Developer options to "430 dp". This set the minimum size to 3x1.

Thanks so much for implementing this feature! 👍🏻
