### ISSUE TITLE
Import from contacts reset event type

### ISSUE THREAD

**Issue by ccoVeille** [m-i-n-a-r/birday#322]
Name day, day of death, wedding… all these settings are nuked and reset to other when reimporting from contacts.

How to replicate:
- import from contacts (assuming you have a contact with a date event set to anything from birthday)
- set its type to anything than birthday by using the app
- import from calendar again
- the event type of modified events will be reset to other

This bugs is a real pain to me, when I add event date to contact then I was to sync app

**Comment by m-i-n-a-r** [comment]
Well, it shouldn't happen. Android contacts app supports birthdays, anniversaries, other and custom event types. Birday can import birthdays, anniversaries and others just fine, while for custom event types, they are saved as "other" too.
So this only applies to death anniversaries (they don't exist in Android contacts app) and custom labelled events. On my side, I never introduced any custom type of event to keep the app simple and the stats meaningful, but I appreciate any suggestion 😄
A possible approach to this is letting the user choose between replacing existing events when importing again, or overwriting them: in this way, you can import a contact, change its type, and import from contacts again without it being overwritten with the wrong type.

**Comment by ccoVeille** [comment]
I'm experiencing the issue for:
- name day (custom on my phone)
- wedding (custom on my phone)
- death date (custom on my phone)

I can share .vcf

I'm unsure about the best workflow, because unless there is a way to review each difference

Because one interesting thing is the ability to update the photo even if the dates didn't change

**Comment by m-i-n-a-r** [comment]
I published a new beta in the Play Store with an experimental option to disable the overwrite of already existing events! This should fix your issue, so I'll close it for now :) try it and let me know, unless you installed the app via F-Droid.

**Comment by ccoVeille** [comment]
I enrolled the beta on Google Play.

![Screenshot_20240618_090405_Birday.jpg](https://github.com/m-i-n-a-r/birday/assets/3875889/30a0dd91-e2a7-469a-b48d-81a820503e55)

I think the version was updated as I see a few changes.

I tried to import, but I didn't see any changes. I used "import from contacts"

**Comment by m-i-n-a-r** [comment]
Yep. you're still in v4.3.0, while the latestt beta is v4.4.0 😄

**Comment by ccoVeille** [comment]
Based on Google play message, I think I will need to wait the next beta version to be released to have it

**Comment by ccoVeille** [comment]
I'm on 4.4.3, and I still have no popup asking me what do to with existing contacts.

I can live with that, but I expected to have something that would solve my import issues

**Comment by m-i-n-a-r** [comment]
You have to select the import strategy in the experimental settings, you can choose to overwrite or ignore duplicates. Regarding the dialog and the manual choice, it's too much coding and new strings. It's on the todo list, but in the "low priority" section at the moment 😞 I have limited free time (like, really limited) and I have to make choices, sadly.

**Comment by ccoVeille** [comment]
Thanks, I found it now. I appreciate.

At least I can import new users easily, and when I want to change something I can use the "overwrite" setting, but I have to fix the event type for some events
