### ISSUE TITLE
battery_optimization_tutorial toast exceeds two lines

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#327]
According to  https://developer.android.com/guide/topics/ui/notifiers/toasts, if your app targets Android 12 (API level 31) or higher, its toast is limited to two lines of text. In this case that means the second part of the instructions is not visible on most current devices, and all future ones. Perhaps there's a better solution?

**Comment by m-i-n-a-r** [comment]
I can see the text on my device, but using bigger text sizes part of the message is unreadable, so you're right. I can move it to a dialog and open the dialog before launching the settings screen, what do you think?

**Comment by DominikNovosel** [comment]
Possibly, but ideally the option would take you to the settings menu immediately. You could move it to a push notification instead, but that'd be easy to miss. The option's description is already pretty long, so I'm not sure if adding it there is a good idea.

**Comment by m-i-n-a-r** [comment]
I'll see if I can find a better solution, but the toast is the only way to display something WHILE the user is doing something outside of the app, sadly

**Comment by DominikNovosel** [comment]
> using bigger text sizes part of the message is unreadable

I should also mention that, at least on my devices, this occurs irrespective of text size. OneUI's toasts, for instance, seem to have a fixed size that applies to both portrait and landscape mode. Curiously, the second line wraps around midway through the toast and leaves a fair bit of empty space. Having thought about it, a push notification seems like an acceptable short term solution, seconded by adding the instructions into the description, assuming it's absolutely necessary to provide these instructions.

**Comment by m-i-n-a-r** [comment]
in 3138cbec2d35a034a891afecec4685b024fca9c7, I simply attached the tutorial to the description itself, it's literally the only way. I didn't remove the toast message though, since on many devices it should be readable. The tutorial is not absolutely necessary, but I receive emails, from time to time, asking how to disable the battery optimization, so it could help someone 😄
