### ISSUE TITLE
Suggestion: Auto SMS on birthday 

### ISSUE THREAD

**Issue by nwrkbiz** [m-i-n-a-r/birday#34]
It would be really handy if it would be possible to configure automatically sent SMS.

**Comment by m-i-n-a-r** [comment]
Hi, and thanks for the advice! The auto SMS feature would require a lot of additional permissions and the phone number together with the birth date and name. I'm trying to keep Birday simple and not invasive, so i can't implement such feature for now. Thanks for asking!

**Comment by geohas** [comment]
What a pity :(

**Comment by nwrkbiz** [comment]
> 

You are right :/
