### ISSUE TITLE
'Edit notes'-dialog shows blank shape behind text selection toolbar

### ISSUE THREAD

**Issue by min7-i** [m-i-n-a-r/birday#343]
### Steps to reproduce

1. Open the details of an event.
2. Tap on 'Notes'.
3. Enter a text.
4. Long-press the entered text to highlight it.

### Expected behavior

The text selection toolbar is displayed.

### Actual behavior

The text selection toolbar is displayed, but a blank shape is visible behind the toolbar and in front of the note dialog partially covering the actual note.

https://github.com/m-i-n-a-r/birday/assets/97251923/0e84a1ef-a3fa-44e6-9024-2f5c83eeb559

### Birday version

4.4.3 (F-Droid)

### Devices

Google Pixel 6a Android 14 (GrapheneOS) | LG G6 Android 9

### Other details

On my LG I also tested the versions 4.2.0 and 4.3.0 where the issue can be reproduced as well.

**Comment by m-i-n-a-r** [comment]
Woah, that's the weirdest bug I've ever seen 😐
And I can recreate it as well! I'll fix it asap, thanks!

**Comment by m-i-n-a-r** [comment]
I'm still investigating, but I can't find a fix. It could depend on the Material Components Google library

**Comment by min7-i** [comment]
I just had a look at it and I assume that this is caused by setting `android:background` for the MaterialAlertDialog styles:
https://github.com/m-i-n-a-r/birday/blob/527de6fde92b4c38a83407648476035d9e70322d/app/src/main/res/values/styles.xml#L79

https://github.com/m-i-n-a-r/birday/blob/527de6fde92b4c38a83407648476035d9e70322d/app/src/main/res/values/styles.xml#L86

I only did a quick test and removing this at least resolved the issue both when using the Monet theme and other themes, but I didn't check any of the other dialogs which are probably influenced by that as well.

**Comment by m-i-n-a-r** [comment]
> I just had a look at it and I assume that this is caused by setting `android:background` for the MaterialAlertDialog styles:
> 
> https://github.com/m-i-n-a-r/birday/blob/527de6fde92b4c38a83407648476035d9e70322d/app/src/main/res/values/styles.xml#L79
> 
> https://github.com/m-i-n-a-r/birday/blob/527de6fde92b4c38a83407648476035d9e70322d/app/src/main/res/values/styles.xml#L86
> 
> I only did a quick test and removing this at least resolved the issue both when using the Monet theme and other themes, but I didn't check any of the other dialogs which are probably influenced by that as well.

Thanks, I had no clue it could be the issue, but you're right! I'll remove this color, even if I'm probably using it to theme the preference dialogs or something similar 😕

**Comment by m-i-n-a-r** [comment]
Fixed this and other theme-related bugs in b04dbb1adb4752b426f0f7505aa9a5b11e2a727a , it was harder than I expected 😥
