### ISSUE TITLE
App keeps closing when importing contacts 

### ISSUE THREAD

**Issue by robsonsobral** [m-i-n-a-r/birday#354]
Thank you so much for the app.

I've been missing events. After check the app, I discovered there's no events anymore and I can't import contacts.

Maybe an update crashed it.

Is there something I can do to help debug?

Thank you!

**Comment by m-i-n-a-r** [comment]
Well that's a super weird issue! 
First thing first, I need more info: 
- actual installed version
- play store or F-Droid?
- are the settings still as you remember them? Or they reset as well?
- device? Android version?

**Comment by m-i-n-a-r** [comment]
Iìll temporarily close this, to keep things clean. Also, a new beta is out, try it! And feel free to reopen it if you want 😄

**Comment by robsonsobral** [comment]
I'm sorry! I missed the github notification!

- Version 4.5.0
- it used to be installed from F-Droid, but i've uninstalled and installed again from PlayStore, without luck;
- I reset everything trying to make it to work again;
- running Android 12 on a Moto g71 5g.

**Comment by robsonsobral** [comment]
Is there anything else we can do to help you debug it, @m-i-n-a-r ?
