### ISSUE TITLE
Birthday notification timers

### ISSUE THREAD

**Issue by Kreuger** [m-i-n-a-r/birday#38]
Hey I work midnight shift so it would be great for me to set reminders for birthdays in the afternoon, when I wakw up. Not sure why you have limited the time frame.

**Comment by m-i-n-a-r** [comment]
I'll be honest: i limited it to avoid problems with am/pm and 24 hours formats 🙂 but it's a stupid reason, I agree. I should improve that option in the next updates!

**Comment by Kreuger** [comment]
I appreciate it. For what its worth, I also prefer the 24 hr clock.

**Comment by m-i-n-a-r** [comment]
In bcddca7bf8766071c2ea77f4f1178fec9707c2af and following commits, i added a timepicker to the app, to choose any hour and minute to receive the notification, without being limited by a set of predefined times 👍

**Comment by Kreuger** [comment]
Thank you!
