### ISSUE TITLE
Add widget option to only show text if next birthday is closer than N days

### ISSUE THREAD

**Issue by breisa** [m-i-n-a-r/birday#39]
Hey,
first of all, I love your app.
The widget looks really nice and I use it on my homescreen to remind me of upcomming birthdays.
At this moment the next birthday is 30 days in the future, which means for the next 30 days I will be reminded of this upcomming birthday every time I unlock my phone. I would love an option to have the widget only show text if the next birthday is closer than N days. This allows the widget to "get out of the way" if no birthdays are upcoming. Additionally, this allows for a more gentle way of beeing reminded, compared to the single notification X days before/on the birthday.
Thank you for developing this app! 😊

**Comment by m-i-n-a-r** [comment]
That's an interesting idea, and I agree with you that it could be an useful feature. I added it to the todo list, I'll see what I can do in future updates!

**Comment by m-i-n-a-r** [comment]
The widget will be completely redesigned in the next update, so i'll close any widget related issue for now. I hope to complete the redesign in one month, more or less.
