### ISSUE TITLE
Add Picture on list on birthdays

### ISSUE THREAD

**Issue by alexandrenavarro** [m-i-n-a-r/birday#40]
Add Picture on list on birthdays

**Comment by alexandrenavarro** [comment]
Add Picture on list on birthdays and potential in the notification if possible.

**Comment by m-i-n-a-r** [comment]
I'm already working on such feature, but i temporarily disabled it in 65e86cda7ebdbbdcc7505e026aa769da626db4db , i should finish it in the next few weeks, but i also have to think how a user can set the image, and so on. Every suggestion is appreciated of course!

**Comment by m-i-n-a-r** [comment]
I finished this feature in 60dd42d53c62575c2ad60093ef2a02812e87110b and other commits lately. It should be available with the next update, in more or less a week! The image is also imported from contacts if available, and it's displayed in the notification. I left an option to completely disable the images and keep the old look of the app, just in case.
