### ISSUE TITLE
Add the last name in addition a first name in the notification

### ISSUE THREAD

**Issue by alexandrenavarro** [m-i-n-a-r/birday#41]
Add the last name in addition a first name in the notification

**Comment by m-i-n-a-r** [comment]
I omitted it for a reason i don't remember at the moment 😕 i'll look into it!

**Comment by m-i-n-a-r** [comment]
Feature added in 81e592908f987a697bed8c54b8b50e7a9f813aad and previous commit. If there's one event in the current day, the last name is shown, also following the preference to show it before or after the name. It will be available with the next update, hopefully in a few weeks!
