### ISSUE TITLE
Allow me to set the birth year as far back as I like

### ISSUE THREAD

**Issue by Kurasami** [m-i-n-a-r/birday#44]
For what it's worth the app is great. However, a lot of the birthdays I want to be reminded of are for people who have passed away. Historical persons for example.

I shouldn't have to use a different app just because you only allow the person entered to be born max 100 years ago.

Please just allow us to write the year. It's faster and makes more sense. If you don't wish to add this as a default feature, please make it something I can enable in the settings.

Do this and I'll fully localise your app in a language you don't currently have as a thanks.

**Comment by m-i-n-a-r** [comment]
This is a date picker limitation. I'll probably have to change the date picker i use due to this and other issues, and I'll surely use a date picker without this limitation. Just stay tuned 🙂

**Comment by Kurasami** [comment]
Thank you mate! Looking forward to it!

**Comment by m-i-n-a-r** [comment]
Done in 0eb6b24e8ad467b70fce3cd44c923f6bb3193b2f , the lower limit is now the year 1500, i think it's enough but i could lower it further if needed. The update containing this should be released in more or less a week!
