### ISSUE TITLE
Add name format strings to the localization table

### ISSUE THREAD

**Issue by Still34** [m-i-n-a-r/birday#54]
## The Problem

Strings involving a person's name become impossible to localize in certain languages if the name cannot be freely moved around in the localized string. 

Let's take `random_chinese_year` for example: the current English string is `Chinese zodiac sign of`, which under the context of the app would become thing like `Chinese zodiac sign of Dave`. This is fine in most Latin-written languages or countries. However, this string becomes impossible or awkward when localized in languages such as Chinese. In Chinese, the subject has to be moved to the front of the sentence in order to make the sentence readable, less awkward, or even to make sense at all. Think of it like `Dave's Chinese zodiac sign`, except in English both are acceptable while in Chinese it is not. 

## The Solution

Add strings involving a subject (e.g., names) as a format string in the string table. The above example would become `Chinese zodiac sign of %s` instead. That way, languages such as Chinese could be written as `%s 的星座`, where the `%s` has to be at the front of the sentence.

**Comment by m-i-n-a-r** [comment]
Yep, you're right, and i have to admit I didn't consider this case at first (probably because I didn't hope in a chinese translation 🙂). I'll try to implement your suggestion in the next update!

**Comment by Still34** [comment]
Haha, yeah that's fair, most people don't write strings with i18n implementation in mind.

**Comment by m-i-n-a-r** [comment]
It was a long refactor, but in commit a5c1c8b0011dae051cecee1d846fc795aca50966 i updated the strings and the code to format the sentences in the stats as you suggested. I only need a chinese translation now 😆

**Comment by Still34** [comment]
And I just so happen to have it *almost* ready!
