### ISSUE TITLE
Bug: Birthdays dates are displaying the wrong date

### ISSUE THREAD

**Issue by pmartiner** [m-i-n-a-r/birday#55]
**Issue:** 
Hi! First of all, I must thank you for the app! I'm trying to leave Facebook and I've found this app to be exactly what I needed to take that step (I love the UI, btw). However, today I added my friend's birthdays for the first time and, although the date input is showing the correct value, the timeline/dashboard is showing them as if their birthdays are one day before they actually are. 

**Expected behaviour:**
The birthdays should display the correct date.

**Additional information:**
UTF offset from where I live: UTC−05:00

**Comment by pmartiner** [comment]
Screenshots
![Screenshot_20210506-222314_Birday](https://user-images.githubusercontent.com/25936810/117393541-e05e0780-aee3-11eb-8878-a2854cc65946.png)
![Screenshot_20210506-222323_Birday](https://user-images.githubusercontent.com/25936810/117393546-e18f3480-aee3-11eb-8210-c59bee8e2fc6.png)

**Comment by m-i-n-a-r** [comment]
Hi there! I wasn't aware of this because it doesn't happen in my timezone (central Europe) and it seems to be a timezone related bug. I'll try to fix it as soon as possible, thanks for letting me know!

**Comment by m-i-n-a-r** [comment]
I should have fixed this issue here 54e8578fde1a31fd3295c04589956029d22aee30 , i tested using different time zones and everything seems to work as expected. I'll update the app tomorrow!
