### ISSUE TITLE
Show in calendar

### ISSUE THREAD

**Issue by PanderMusubi** [m-i-n-a-r/birday#57]
Please provide an option to show birthdays in the calendar such as the apps https://github.com/SufficientlySecure/birthday-calendar and https://github.com/saschpe/BirthdayCalendar do.

**Comment by m-i-n-a-r** [comment]
I'm not sure where to add this screen and if it's really useful for the users, but I'll think about it, thanks for the suggestion!

**Comment by 1-minute-to-midnight** [comment]
I second this request. I would like to import my birday's to my nextcloud instance. They expect iCalendar format....so I think that is the format you have to convert the birday format to to import into calendars. 

(I'm no expert btw.........love your apps)

**Comment by m-i-n-a-r** [comment]
Well, all i can do is show the events on the system calendar optionally, and I'm not even sure of how to do it (i sent an email to the developer of birthday calendar but he didn't respond). Other import/export mechanics are out of my knowledge, I'm just trying to add a csv export feature at the moment 😅

**Comment by albertopasqualetto** [comment]
I think that if you set the birthday of your contact (I think it works for every device/calendar), then people just have to enable the relative calendar in their app and it is done.

**Comment by m-i-n-a-r** [comment]
I'll close this for now. I don't plan to add additional permissions (write calendar would be required for this feature to work), and i want Birday to be an hub for yearly events, so there's no point in writing the events on another app, from my point of view. 😄
