### ISSUE TITLE
Option to disable zodiac / star sign

### ISSUE THREAD

**Issue by neubland** [m-i-n-a-r/birday#59]
Displaying the zodiac signs may not be an big problem for many people, but it would still be nice to be able to deactivate it. Some people are quite opposed to astrology.

**Comment by m-i-n-a-r** [comment]
I'm opposed to astrology too, i used them just to improve the design and add some information. But i'll keep that in mind, even if disabling them would make some screens look quite empty :)

**Comment by m-i-n-a-r** [comment]
Done in 844b249cb7be592c2558fed9ead4f862026d1f06, and available starting from v4.2.0 (i'll release it in december probably)
