### ISSUE TITLE
suggestion: change selection behavior

### ISSUE THREAD

**Issue by iroQuai** [m-i-n-a-r/birday#6]
atm, long-press gives stats about the entry, short-press gives the options to edit or delete.

I'd like to suggest to combine the short-press and long-press menus to one menu. Could just look like the long-press menu, but with the two buttons (edit/delete) at the bottom. or even in the top-right as icons (trashcan and pencil, for instance)

this leaves the long-press unused. could perfectly be repurposed as a way to start the selection process (selecting multiple items for bulk delete or maybe even bulk edit? although that probably would rarely be used)

**Comment by m-i-n-a-r** [comment]
Done in 2c52b5f4f14cbca4fd49efadc55e434d1d80de67 . Regarding the multiselection mode, i'll probably add an option to delete every entry, since deleting a small number of events is relatively fast, to keep the app simple to use, at least for now 👍
