### ISSUE TITLE
Feature Request: Cloud Backup

### ISSUE THREAD

**Issue by neubland** [m-i-n-a-r/birday#60]
It would be great if there was an option to do a Cloud Backup. This could be done via using Google Drive or the 25MB-Auto-Backup included in Android, any cloud solution would help.

**Comment by m-i-n-a-r** [comment]
There is already! The app backups the data to Google Drive automatically (sometimes it takes time, but it doesn't depend on Birday) and, if you do a manual Birday backup, you can share the backup file using any application, including Google Drive, Email, Telegram and so on 😄
