### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by roshavagarga** [m-i-n-a-r/birday#61]
Would be nice if there was a DD/MM/YY mode for input.

**Comment by m-i-n-a-r** [comment]
It depends on your locale! It should automatically adapt to it. For example, since I'm in Europe, i have such format.

**Comment by roshavagarga** [comment]
That it does, but I don't use my phone in my native language/locale, the default language is American English.

**Comment by m-i-n-a-r** [comment]
I see. Sadly, adding an option to manually override the date format requires a lot of work and removes the automation, which is not optimal to make the app simple to use. Maybe there's a way to change the geographical area while keeping the same language, I'll investigate 👍

**Comment by roshavagarga** [comment]
If the latter is an option, I'd be grateful, but if it's cumbersome to implement, don't waste your time on such a minor feature :)

**Comment by pityalvarez** [comment]
Any news is appreciated because an in-app language selector seems more difficult to add

**Comment by m-i-n-a-r** [comment]
With the next update, i'll add the Android 13 per-app language selection support, which means that you can select a language for Birday directly from settings. Of course this is limited to Android 13 and above, and that's probably an issue for most users still running 11 and 12.
