### ISSUE TITLE
Numbers and Symbols aren't allowed in name

### ISSUE THREAD

**Issue by AmasaDelano** [m-i-n-a-r/birday#62]
When I try to enter the legal first name of someone I know:

Su3an

The app gives the error that "Numbers and Symbols aren't allowed in names."

Unfortunately, real names have no such restrictions. That validation should be turned off, and any character should be allowed in the name fields.

Also, related, but different (I can open a separate issue for this if you want):

When I enter a first name or last name with multiple words, or with an apostrophe in it, the app auto-capitalizes the separate words. This is not always correct. For example, this legal name

Ja’net

Gets corrected to

Ja'Net

Which is not her legal name. Also, the last name

van Zijl

Gets corrected to

Van Zijl

Which is not their legal last name, and is therefore incorrect.

Do these seem like changes you'd be willing to accept for Birday? If so, let me know, and I can try to figure out how to make these changes in the code. But I don't want to bother if they for sure wouldn't be accepted.

Thank you! :)

**Comment by m-i-n-a-r** [comment]
Sorry for the late reply. Well, i had no idea. Tha capitalization is always applied to any words and as you said, the only allowed special characters are the emojis. I'll surely remove the auto capitalization at this point.

Regarding the numbers, aside from Elon Musk's son, i had no idea a person could have a number in his/her legal name. I'll allow numbers, but still not symbols probably. Thanks for the suggestion!

**Comment by m-i-n-a-r** [comment]
I should work on this issue in the next few days, unless you're about to submit a pull request. If that's not the case, i'll fix this soon!

**Comment by AmasaDelano** [comment]
I haven't put aside the time to work on this yet. So I've got no pull request or changes at all about to submit! XD

**Comment by m-i-n-a-r** [comment]
No problem, I'll take care of it soon 🙂

**Comment by m-i-n-a-r** [comment]
Fixed it, finally. In 3255df189634f3111ba3c700e7bb331e80c51463 and following commits. Now you have an almost complete freedom when entering first and last name 👍
