### ISSUE TITLE
Import contacts bug

### ISSUE THREAD

**Issue by faan11** [m-i-n-a-r/birday#64]
I have Android 10 and i'm using birday version 2.1.0 .

I imported a vcf file using Contact app in the contact list of the device. Each contact in this file has a display name and a birthday.   
Once imported, i tried to import these contacts using birday but none of them were recognized.

Is there any way to solve this issue? A simple solution can be to let the user imports contacts using a vcf file.

**Comment by m-i-n-a-r** [comment]
Are you sure that the birthday results as a proper birthday in the contacts app? Birday only recognizes contacts with a name and a birthday, as you said (also, even if is problably useless, did you try a reboot?). Regarding the vcf import, surely it could be a good feature, but i prefer to improve the contact import to work properly when a vcf is imported in the contacts app itself. Let me know!

**Comment by faan11** [comment]
My vcf files has the following entries:

`BEGIN:VCARD
VERSION:4.0
FN:Name
N:Name
BDAY;VALUE=DATE:19500101
UID:theid
END:VCARD`

https://tools.ietf.org/id/draft-ietf-vcarddav-vcardrev-02.html#BDAY
https://tools.ietf.org/id/draft-ietf-vcarddav-vcardrev-02.html#N 
https://tools.ietf.org/id/draft-ietf-vcarddav-vcardrev-02.html#FN

**Comment by m-i-n-a-r** [comment]
Could you please try again with v3.1.0? I'm temporarily closing this, but feel free to reopen if it still doesn't work of course.

**Comment by faan11** [comment]
Is it uploaded to F-droid? Where i can find the latest apk?

**Comment by m-i-n-a-r** [comment]
The update should be available soon, F-Droid should fix a couple things, as far as i know 😄

**Comment by faan11** [comment]
I saw the update in the F-droid app. i'll check later this feature
