### ISSUE TITLE
Add translation guide

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#66]
Writing a translation guide would encourage more people, especially beginners like myself to translate Birday to other languages and help explain some of the specifics required to do so.
Some things such a guide should probably include:
* The procedure to acquire strings.xml
* The meaning of special symbols and why they should be left where they are
* How to use escaped characters and what they are for, e.g. won't  vs.  won\\'t
* How to use language specific plurals, as excellently documented by https://developer.android.com/guide/topics/resources/string-resource#Plurals
*  Explain strings that may be difficult to translate without context, along with where they might appear
* How to submit a pull request to add the translation
* Some general tips and tricks

You know, things that are considered common knowledge among professional translators.

**Comment by m-i-n-a-r** [comment]
Yep, that's a good idea. I'll add it to the readme or to the wiki as soon as i can 👍

**Comment by m-i-n-a-r** [comment]
https://github.com/m-i-n-a-r/birday/wiki/Translate-the-app here it is. I linked it in the README, and it should help any future translator. Thanks for the advice!

**Comment by DominikNovosel** [comment]
Of course, glad I could help! I'll take a look and see what I can improve.
