### ISSUE TITLE
Add in-app language selector

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#67]
I'm not sure if I'm the only one with this problem, but I prefer to keep my system language in English because my native language is very poor in IT terminology. But when I use Birday, I can't quickly work out things I don't often talk about in English such as dates and astrological signs. Seeing as though Birday pulls dates and their translations from the system, how difficult would this be to implement?

**Comment by m-i-n-a-r** [comment]
A similar feature was requested before, and the problems are mainly two:
1) Google discourages the use of in-app language selectors in its guidelines
2) It's not easy to implement

With that being said, i'm part of the same problem: sometimes i use english (US) even if my native language is italian. I'll investigate on a discreet and user friendly way to implement this feature, but i can't make promises 😄

**Comment by DominikNovosel** [comment]
Okay, thanks!

**Comment by russellbanks** [comment]
> I'll investigate on a discreet and user friendly way to implement this feature, but i can't make promises 😄

From my experience with this, there are libraries that can help with in-app localisation changes. I've used [Localization](https://github.com/akexorcist/Localization) before and I recently came across [Locale Helper Android](https://github.com/zeugma-solutions/locale-helper-android) (I haven't tried it so cannot vouch for it per se). The only thing to consider is that regardless of what library is used, you would have to prevent language split for abb files (documented on each library about how to do this) which would result in a larger file size.

**Comment by m-i-n-a-r** [comment]
Thanks for the suggestion! Regarding the issue with the aab, i still release the app in apk format (the size is only 3MB after all) so i shouldn't have this problem 👍

**Comment by m-i-n-a-r** [comment]
Update: from Android 13 on, Birday will support the "per-app language" feature (eb0b5a57cfa294861eb0bbc4114acc0ca518e889 and following commits). This means that you will be able to change the language individually for Birday from the system settings. That's one more reason to avoid wasting time in implementing an in-app language selector, imho. I understand that Android 13 is only available for pixel and a few other devices, but it's just a matter of time 😄
