### ISSUE TITLE
suggestion: allow other anniversaries

### ISSUE THREAD

**Issue by iroQuai** [m-i-n-a-r/birday#7]
this app is fantastic! I always forget birthdays and google contacts clutters the list too much with insignificant dates. 

other than birthdays, it would be fantastic to also have the option to add other anniversaries, like weddings.  and maybe even deaths? (so I don't forget to send my condolences. although I realise that the festive icons do not really match this type of event. )

Now that I think of it, allowing other events then birthdays do mess with the statistics. it's probably needed to let the user decide if it's a birthday or some other kind of event. that way you could only use the birthday-entrys for stats.

**Comment by m-i-n-a-r** [comment]
Birday 3.0 (finally) supports anniversaries, death anniversaries, name days and other. It's currently available in open beta, and i should release it in the stable channel soon. I can close this issue, after almost 2 years 😄
