### ISSUE TITLE
Hint texts are blocked on the home page and the favorites page

### ISSUE THREAD

**Issue by yuhuitech** [m-i-n-a-r/birday#74]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the home page and the favorites page, **hint texts are blocked by the round button below**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 2.1.0, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts in those tab buttons, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting and then open this app
2.click the first tab button and then click the second one on the navigation bar at the bottom of the screen
3.this kind of error could be seen on two pages

**Screenshot**

(The blocked parts are marked in red)

<img src="https://user-images.githubusercontent.com/25502419/130936252-b458a825-632c-4aea-b2c5-eb871f0bb618.png" alt="copy" width="250"/>   <img src="https://user-images.githubusercontent.com/25502419/130936256-f1226c75-b859-4816-a90e-826694746196.png" alt="copy" width="250"/> 

**Environment**

1. Version of Birday: 2.1.0
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by m-i-n-a-r** [comment]
Fixed (by you, thanks!) In commit 87d50c87e02cab36db70ac1e9d46b64f630c658a
