### ISSUE TITLE
Add birthday subevents

### ISSUE THREAD

**Issue by roshavagarga** [m-i-n-a-r/birday#76]
In some countries, name days are considered equal to birthdays or close to it - hence it's customary for people to note down people's birthdays, as well as name days. Having a custom field to add these in (since there might be more than 1, I have two per year) would be a welcome addition.

**Comment by m-i-n-a-r** [comment]
Thanks for the advice! I'm planning to add the support for different types of event, I'll just have to decide if the name day is an additional field or a completely different event.

**Comment by m-i-n-a-r** [comment]
Birday 3.0 (currently in open beta) supports different event types (including name days). Separate the events (even if they're about the same person) is important to keep things organized and make the stats work correctly.
