### ISSUE TITLE
Manually Import events from calendar.

### ISSUE THREAD

**Issue by bagarwa** [m-i-n-a-r/birday#77]
I don't have all birthday's in my contacts. For some acquittances, I have birthdays saved only in calendar, but I don't have these people saved in my contacts. Thus, a useful feature for me would be - ability to import events from Calendar.

Flow - 

1. I tap "Import from calendar" button.
2. A list of calendar events show up. 
3. I tap the event I want to import. 
4. Birday populates the fields of a new birthday reminder entry, using the data of this event.

**Comment by m-i-n-a-r** [comment]
The "import from calendar" feature is a debated one since last year, i'm currently trying to understand how can i manage the calendar import and if i can automate something. It's quite tricky compared to the contacts import, that's for sure. I'll keep you updated 😄

**Comment by m-i-n-a-r** [comment]
I developed a basic calendar import in fd2dfc9fd1c969fe8a588904efe2453fe24aa25f and following commits. It works like in other apps (birthday calendar for instance). Basically, it finds any yearly event and imports it using the title as name and the description as note field. I can't, like other apps, recover the year and the type of the event. Feel free to open additional issues when you try this feature (should be available in next release)
