### ISSUE TITLE
Show next N number of birthdays in the widget, along with photos.

### ISSUE THREAD

**Issue by bagarwa** [m-i-n-a-r/birday#78]
The widget currently is very bare bones. My suggestion is - adding some more features to it.

1. Instead of showing just one next birthday, show N number of birthdays; for example, show next 5 birthdays. Or birthdays in the next 30 days.
2. Instead of being just all text, show the contact photos on the left or right side of each row.

**Comment by m-i-n-a-r** [comment]
Thanks for the advice! I tried to keep the widget simple, but you're right. I already wanted to add the image, but another good idea could be to show more events if the widget has a size such as they can fit.

**Comment by m-i-n-a-r** [comment]
The widget will be completely redesigned in the next update, so i'll close any widget related issue for now. I hope to complete the redesign in one month, more or less.
