### ISSUE TITLE
suggestion on unknown birth years

### ISSUE THREAD

**Issue by iroQuai** [m-i-n-a-r/birday#8]
it would be great allowing not having a birth year! Now a lot of my contacts are from the year 2000, the standard import choice if nothing is mentioned). it's a bit strange to see a notification for my grandma's 20th birthday :) 

Brainstorming further on that idea: if the birth year is not known, make it possible to add someone's age! This could be calculated back to the right year so from that moment on there's no doubt on their age again.

**Comment by m-i-n-a-r** [comment]
I had to heavily modify some parts of the app, but i did it, the last commit about this modification is 436cec674a65dcde3bbdfbe1b27385e8c913aae7 , where i removed the reference to the default year when importing. I could surely improve it further, but it works ok 😃

**Comment by iroQuai** [comment]
Thanks a lot!!!
