### ISSUE TITLE
Notification improvements

### ISSUE THREAD

**Issue by bagarwa** [m-i-n-a-r/birday#81]
Right now, when a birthday reminder notification pops up, the text on the notification says "upcoming birthday! Name Surname". This isn't very helpful, tbh. I can't tell whether the birthday is today, tomorrow, or day after. Instead, the notification should say "Upcoming birthday tomorrow! Name Surname" or "Birthday in 2 days! Name Surname" or "Birthday today! Name Surname."

Showing the contact's photo on notification would be cool too.

Also, can you please make the notification sticky, so that they can't be accidentally swiped away? Add a "dismiss" action button to it and only clicking that should dismiss the notification.

**Comment by m-i-n-a-r** [comment]
I simplified the notification text in cf72ed2749500042b70e3453c9489b3a9181005d and following commit. I'll keep the current behavior though, following the Google guidelines. I'll reopen this issue is someone else asks for the same behavior
