### ISSUE TITLE
Additional notification option per contact

### ISSUE THREAD

**Issue by bagarwa** [m-i-n-a-r/birday#82]
Right now, notification settings are global and apply to all contact birthdays. But not all contacts are equally important. For most contacts, a reminder on the day of birthday is enough. For few other close friends, I'd like to get an additional notification 1 day before. For family members, I'd like to get another additional notification 1 week before. 

Thus, instead of being a global setting, it'd be very useful if you can make "additional notification" a per contact setting.

**Comment by shkiss** [comment]
I would appreciate a similar functionality, which might satisfy @bagarwa. 
Currently you have a favourite option, and the ability to only notify for favourites. Instead, I would like to always notify on the day, and additionally notify favourites a week before.
I propose the "Favourites only" switch be changed into another "Additional favourites notification" selection.
I believe this usage sould be common.

**Comment by m-i-n-a-r** [comment]
Well that's a good idea for sure, and it's easier to implement for me. I'll see what i can do in future updates!

**Comment by bagarwa** [comment]
Hi. Just following up to see if this is still in the plans. Happy Holidays!
