### ISSUE TITLE
contacts

### ISSUE THREAD

**Issue by ueen** [m-i-n-a-r/birday#83]
Is there a way just to add the birthdays to existing contacts easily? This way they would also be displayed in the calendar app. Alternatively there could be an option to add contacts, because realistically you would have the phone number of people you want too congratulate, right? 

Maybe contact import should also be executed automatically on first start up, took me a while to find it in settings.

**Comment by m-i-n-a-r** [comment]
The contact import is mentioned in the first launch tutorial, you probably skipped it :)
Regarding the phone number or the "save as contact", i have many birthdays of people with no phone number (mostly children) and while I can "easily" read from the contacts, writing to them starting from a name and a birthday could be hard. I'll see what I can do, I'll reopen the issue for any news. Thanks for the suggestion and for trying the app!

**Comment by ueen** [comment]
I would suggest being able to select from contacts and then writing to them, it's kind of hard on my pixel, first I can't search and edit, I have to scroll to the contact and then it's kind of complicated with the field.
