### ISSUE TITLE
Birthdays this month

### ISSUE THREAD

**Issue by betsythefc** [m-i-n-a-r/birday#84]
Hello! I'd love an option to also send a notification on the first of the month that let's me know whose birthday is coming up with month.

For example:

- November 1st, notification pings
- Says "N birthdays this month!"
- Tapping takes to the main screen, maybe with only the birthdays this month.

If there are only one or two birthdays, perhaps it says who in the notification, but a default behavior being the number of birthdays this month, to the main screen of the app would be fantastic to help me keep these things in my head.

**Comment by m-i-n-a-r** [comment]
I'm working on something similar, but without the notification at the moment. Simply, I'm developing an "overall screen". But a notification could be an option, so I'll see what i can do! Thanks!

**Comment by m-i-n-a-r** [comment]
I added a 10 days overall row in the favorite screen, and i'm developing a "yearly overview", but it will take some time and the next update will contain only the 10 days overall

**Comment by m-i-n-a-r** [comment]
The overall screen is complete. d9249806e5fa970086311f65a3e475ff0f3009c9 and many previous commits. I developed a completely custom component to show the entire year and the events in the year.
