### ISSUE TITLE
Long term support version

### ISSUE THREAD

**Issue by DominikNovosel** [m-i-n-a-r/birday#85]
Hi, following some experimentation with compiling the app myself, i managed to create a build of Birday based on the latest stable source with all the translations from master backported into it.
 I think it would be good if I created a fork of Birday based on the latest stable release where i would invite existing translators to push their changes as well as to the upstream code. I'd then publish a new build in Releases every so often so that the up to date translations are readily available to everyone. I won't publish the app to the Play Store myself because it would be a huge hassle to me and probably result in brand dilution, so i suppose you could do that yourself. For sideloading the APK though, i intend to write user friendly instructions that would make it very clear how to install the app and that the data needs to be backupped before updating. As far as I'm aware, all of the above is compliant with the GPL.
 Of course, I'm very much a beginner and all this might be more complicated than I'm aware of (opinions are very much welcome) but I think that this would be beneficial to both translators and end users.

Best regards, Dominik

**Comment by m-i-n-a-r** [comment]
That's fine for me, every help is appreciated and the license shouldn't be a problem. As you may have noticed, I'm having little to no time lately, and i barely managed to finish one project (another app to manage qr and bar codes, not open source atm). I can't make promises, but I'll do my best to keep Birday alive and keep improving it, i promise!

**Comment by DominikNovosel** [comment]
Thanks! I did, however, notice several caveats. Making a fork based on the stable release and replicating what I did for the LTS would require a bunch of clumsy file management through GitHub, I'll see what I can do about that, perhaps i can upload it as is and archive the repo after the next release and fork that (how's it going with that release?). Second, I'm not sure if I understood correctly, but Birday supports Android 8 and up, and to compile for a given version, i need to install its respective SDK, right? Maybe make the wiki page more clear about this.

**Comment by DominikNovosel** [comment]
The repo should be here: https://github.com/DominikNovosel/Birday-LTS.
I'll be working on the instructions over the next few days. Thank you for your support!

**Comment by DominikNovosel** [comment]
I've finally managed to upload my work and make some decent documentation. I'm hoping this will also help you keep the translations up to date, do you think you could periodically clone the repo and push out updates to Google Play? It might also help if you link to the repo in the README and translation instructions.

**Comment by m-i-n-a-r** [comment]
Nice work and sorry for the late reply! Yep, i'll link the repo in the readme. I was also planning to work on a separate branch to keep the main branch clean and working, but that's another good solution. Regarding the translations, i should find a way to write every missing string for every language automatically, but i have no idea how to do it at the moment 😄 
Happy new year though! I hope to deliver the new update (Material You, support for other event types and a lot more) in approximately a month!

**Comment by DominikNovosel** [comment]
Thanks! I'll be rendering 2ed78da4267879f760617e0735a93d6917c19ed8 to LTS soon, do you think you can push out that version to Google Play until the next release?

**Comment by m-i-n-a-r** [comment]
Sorry, i forgot to answer :) I'm quite close to finish the new update (there's still something missing, but i decided to break it into 2 different updates, to minimize the risk of tremendous bugs and nuclear explosions). The biggest problem are the missing translation, i still have to decide whether to translate them on my own (with terrible results) or leave them untranslated and wait 😄

**Comment by m-i-n-a-r** [comment]
Version 3.0.0 has been released in the Open Beta channel. From now on, Birday will have a develop branch and a stable main branch, to avoid messing up the code while adding new features

**Comment by DominikNovosel** [comment]
Great! I'll archive my LTS repo when I get home and get to beta testing soon after. So, the master branch can now generally be considered stable? Will this facilitate hotfixes such as bugs and translations? I'd distribute a build to some family members and see if everything is alright, but I'm a bit busy. In general, however, it might be useful to attach an APK to each release and/or hotfix for quicker testing.

**Comment by m-i-n-a-r** [comment]
Yep, i'll only merge finished features in the master branch, so it should always contain 100% working code after the definitive release of v3.0 in the stable channel and on F-droid. I'll see if i can configure the Github Action to also output the apk after each commit or merge. 👍

**Comment by DominikNovosel** [comment]
Awesome, thanks! Should future translation fixes be committed to master or development? Can you update the wiki with this information?

**Comment by m-i-n-a-r** [comment]
The translations shouldn't be a problem, since they are updated starting from the master branch itself. From now on, every new feature will be merged in the master branch with the only translations i can do by myself (english, italian, spanish) and therefore translated to other languages😄

**Comment by DominikNovosel** [comment]
That... doesn't really answer my question. I was asking, if I were to update or add a translation by modifying the respective values.xml, which branch should my pull request be pointed to, the stable or unstable branch?
