### ISSUE TITLE
Unnecessary cursor animation

### ISSUE THREAD

**Issue by AnilSeervi** [m-i-n-a-r/birday#86]
When clicked on add new birthday icon 🎉, A cursor appears on the end of `New birthday` text in the popup for about 2sec.

**Comment by m-i-n-a-r** [comment]
Yep, it's a known issue and depends on material Dialogs, the library I'm using to spawn the bottom dialogs. There's already an issue opened, but the development of material Dialogs seems stuck. And that's a pity. Thanks!
