### ISSUE TITLE
Disable animated notification icon

### ISSUE THREAD

**Issue by krmax44** [m-i-n-a-r/birday#87]
I find the waving/blinking bird in my notifications quite distracting and would love an option to disable it. Thanks for the useful app!

**Comment by m-i-n-a-r** [comment]
That's not easy at it seems. If i receive further requests for this feature, i'll work on it! Thanks for the suggestion!

**Comment by m-i-n-a-r** [comment]
Closing for now, i'll reopen if i receive another request for this improvement
