### ISSUE TITLE
Birthdays imported from phone contacts

### ISSUE THREAD

**Issue by chillypeppe** [m-i-n-a-r/birday#9]
The feature "Import birthdays from Google" also imports them from the phone storage (I don't have contacts saved in my google account, but the app still managed to import them from the storage). I think it would be better if it was called "Import birthdays from the phone" or something like that, since it can be confusing.

The app is great btw

**Comment by m-i-n-a-r** [comment]
You're right, i'll fix this in the next few days

**Comment by TheLastGimbus** [comment]
For me, this option doesn't find any birthdays - even tho [BirthDayDroid](https://f-droid.org/packages/com.tmendes.birthdaydroid) finds them fine

Also, in my case, I would like to store birthday data in my contacts to avoid app-lock-in (thanks to it, I could now move from BrithDayDroid to your app :tada:) - so a "contacts sync" rather than one-time "import" would be nice :nice:

**Comment by m-i-n-a-r** [comment]
Well, import the contacts again will act as a sync, but if a contact has a different birth date, a double will be created. The name alone is not enough to determine if the event is about the same person, but i'll think about it, a sync could be useful as you said. Regarding the name, the original request of this issue, i should modify it in 1.8. I didn't in 1.7 to avoid modifying every translation 😄

**Comment by TheLastGimbus** [comment]
It could be implemented as "using contacts as a database" - I don't know how technically easy/possible it is (in your app), but that's the approach that many FOSS apps take on tasks like that:

For example, notes apps that store notes as plain markdown files - so there is no app-lock-in, and you can still easily edit them by hand

**Comment by m-i-n-a-r** [comment]
Solved in a2c9343b375647caf2d85a8e8a77a86fd7f018ce . Now There's no reference to Google Contacts, since as you said the import regards every contact provider, thus even non Google-saved contacts.
